bin2cpp.o: bin2cpp.cpp ../../config.h ../../libdjvu/GURL.h \
  ../../libdjvu/GString.h ../../libdjvu/DjVuGlobal.h \
  ../../libdjvu/GContainer.h ../../libdjvu/GException.h \
  ../../libdjvu/GSmartPointer.h ../../libdjvu/atomic.h \
  ../../libdjvu/Arrays.h ../../libdjvu/GThreads.h ../../libdjvu/GString.h \
  ../../libdjvu/BSByteStream.h ../../libdjvu/ByteStream.h \
  ../../libdjvu/ZPCodec.h
