bin2cpp.o: bin2cpp.cpp ../../config.h ../../libdjvu/GURL.h \
  ../../libdjvu/GString.h ../../libdjvu/DjVuGlobal.h \
  ../../libdjvu/GContainer.h ../../libdjvu/GException.h \
  ../../libdjvu/DjVuGlobal.h ../../libdjvu/GSmartPointer.h \
  ../../libdjvu/DjVuGlobal.h ../../libdjvu/Arrays.h \
  ../../libdjvu/GException.h ../../libdjvu/GSmartPointer.h \
  ../../libdjvu/GThreads.h ../../libdjvu/DjVuGlobal.h \
  ../../libdjvu/GException.h ../../libdjvu/BSByteStream.h \
  ../../libdjvu/ByteStream.h ../../libdjvu/Arrays.h \
  ../../libdjvu/GException.h ../../libdjvu/ZPCodec.h \
  ../../libdjvu/GContainer.h
