.\" Copyright (c) 2001 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\"                    AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVIEW 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.SH NAME
djview \- Standalone DjVu viewer

.SH SYNOPSIS
.BI "djview [" "options" "] [" "djvufile" "]"

.SH DESCRIPTION
Standalone viewer for DjVu files.  
Features include navigating documents,
zooming and panning page images, 
producing and displaying thumbnails,
searching documents for particular words in the hidden text layer,
copying hidden text to the clipboard,
exporting page images as
.SM PNM
files, 
saving pages and documents as bundled or indirect multi-page files, 
and printing page and documents to Postscript printers.

.SH OPTIONS
.TP
.B "-help"
Display a brief help message.
.TP
.BI "-page=" "pagenum"
Open page
.I pagenum
of the document.
.TP
.BI "-style=" "stylename"
Specify the graphical user interface style.
Recognized values for
.I stylename
depend on the installed version of the Qt toolkit.
Common style names include
.BR windows ,
.BR motif ,
.BR motifplus ,
.BR sgi ,
.BR cde ,
and
.BR platinum .
.TP
.BI "-fullscreen, -fs "
Start djview in full screen mode.
This only works if you also provide a DjVu file name
on the command line.
.TP
.BI "-geometry=" "geom"
Specify the initial window size.
The
.SM X11
geometry specification
.I geom
often has the form
.BI "" w x h + x + y
where 
.IR w " and " h
are the window width and height,
and
.IR x " and " y
indicate the window position.
.TP
.BI "-display=" "disp"
Specify that the 
.B djview
windows should appear on the 
.SM X11
display 
.IR disp .
.TP
.BI "-fn " "fontname"
Specify the name of the default font used
for buttons and menus.
.TP
.BI "-bg " "color"
Specify the default background color.
.TP
.BI "-fg " "color"
Specify the default foreground color.
.TP
.BI "-btn " "color"
Specify the default button color.
.TP
.B "-visual TrueColor"
Force the use of a TrueColor visual on a 8 bit display.
.TP
.B "-ncols " "count"
Limit the number of colors allocated in the color cube 
on a 8 bit display. The default is 216.
.TP
.B "-cmap"
Cause 
.B djview
to install a private color map on an 8-bit display.
.TP
.B "-fix"
Checks the files
.B $HOME/.mailcap 
and
.B $HOME/.mime.types
and attempt to reconstruct sensible DjVu entries.
This is sometimes useful to make the DjVu plugin work.

.SH USAGE

Most features can be accessed using the menus, the toolbar, or the pop-up menu.
The pop-up menu is shown when the right mouse button is depressed over a DjVu
image.  The toolbar is usually located at the bottom of a DjVu image.  The
preference dialog provides the option to disable to toolbar or set the
"auto-hide" mode.

The following keyboard shortcuts are recognized:
.PP
.TS
center,box;
lfB lfB
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
.
Key	Action
=
1,2, and 3	Change zoom to to 100%, 200% and 300% respectively.
Up, Down, Left, Right	Scroll the image in the given direction.
Home	Display top left corner of the image.
End	Display bottom right corner of the image.
Control+Home	Go to the beginning of the multi-page document.
Control+End	Go to the end of the multi-page document.
Space, Return	Scroll down or go to next page.
Backspace	Scroll up or go to previous page.
Page Down	Go to the next page.
Page Up	Go to the previous page.
+, -	Zoom in and out.
W	Select the "Fit Width" zooming mode.
P	Select the "Fit Page" zooming mode.
G	Display the "Goto page" dialog box.
F, F3, CTRL+F	Search the hidden text layer.
CTRL	Show the magnifier lens.
.TE
.PP

.SH CREDITS
This program was written by Andrei Erofeev <andrew_erofeev@yahoo.com>
and was then improved by Bill Riemers <docbill@sourceforge.net> and
L\('eon Bottou <leonb@users.sourceforge.net>.

.SH SEE ALSO
.BR djvu (1),
.BR ddjvu (1),
.BR nsdejavu (1)
