.\" Copyright (c) 2001 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\"                    AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVIEW3 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.SH NAME
djview3 \- Standalone DjVu viewer

.SH SYNOPSIS
.BI "djview3 [" "options" "] [" "djvufile" "]"

.SH DESCRIPTION
Standalone viewer for DjVu files.  
Features include navigating documents,
zooming and panning page images, 
producing and displaying thumbnails,
searching documents for particular words in the hidden text layer,
copying hidden text to the clipboard,
exporting page images as
.SM PNM
files, 
saving pages and documents as bundled or indirect multi-page files, 
and printing page and documents to Postscript printers.

.SH OPTIONS
.TP
.B "-help"
Display a brief help message.
.TP
.BI "-page=" "pagenum"
Open page
.I pagenum
of the document.
.TP
.BI "-style=" "stylename"
Specify the graphical user interface style.
Recognized values for
.I stylename
depend on the installed version of the Qt toolkit.
Common style names include
.BR windows ,
.BR motif ,
.BR motifplus ,
.BR sgi ,
.BR cde ,
and
.BR platinum .
.TP
.BI "-fullscreen, -fs "
Start 
.B djview3 
in full screen mode.
This only works if you also provide a DjVu file name
on the command line.
.TP
.BI "-geometry=" "geom"
Specify the initial window size.
The
.SM X11
geometry specification
.I geom
often has the form
.BI "" w x h + x + y
where 
.IR w " and " h
are the window width and height,
and
.IR x " and " y
indicate the window position.
.TP
.BI "-display=" "disp"
Specify that the 
.B djview3
windows should appear on the 
.SM X11
display 
.IR disp .
.TP
.BI "-fn " "fontname"
Specify the name of the default font used
for buttons and menus.
.TP
.BI "-bg " "color"
Specify the default background color.
.TP
.BI "-fg " "color"
Specify the default foreground color.
.TP
.BI "-btn " "color"
Specify the default button color.
.TP
.B "-visual TrueColor"
Force the use of a TrueColor visual on a 8 bit display.
.TP
.B "-ncols " "count"
Limit the number of colors allocated in the color cube 
on a 8 bit display. The default is 216.
.TP
.B "-cmap"
Cause 
.B djview3
to install a private color map on an 8-bit display.
.TP
.B "-fix"
Checks the files
.B $HOME/.mailcap 
and
.B $HOME/.mime.types
and attempt to reconstruct sensible DjVu entries.
This is sometimes useful to make the DjVu plugin work.

.SH USING DJVIEW3 AS A BROWSER PLUGIN

The djvulibre browser plugin works by invoking
a standalone DjVu viewer with the special option
.BR -netscape .
See the man page 
.BR nsdejavu (1)
for more details.

When 
.B djview3
is invoked by the djvulibre browser plugin,
a number of options can be specified as 
.SM CGI
style arguments in document 
.SM URL
according to the following template:
.IP "" 3
.BI "http://server/dir/file.djvu?djvuopts&" "keyword=value" "&" "keyword=value" "&" "..."
.PP
The DjVu browser plugin only recognizes keywords that appear
after the word
.BR djvuopts .
Unrecognized keywords are silently ignored.
The following keywords are recognized:
.TP
.BI passive=(yes|no)
Cause the image to be displayed in a manner similar to an ordinary web image.
The default zoom factor is changed to "Fit Page".
The toolbar, the pop-up menu, the scroll bar, and the
keyboard shortcuts are disabled.
The default is no.
.TP
.BI scrollbars=(yes|no)
Enable or disable the presence of scroll bars when the full
image size exceeds the plugin window size.  The default is yes.
.TP
.BI menu=(yes|no)
Enable or disable the pop-up menu.
The pop-up menu is enabled by default.
.TP
.BI keyboard=(yes|no)
Enable or disable the DjVu plugin keyboard shortcuts.
The default is yes (enabled).
.TP
.BI frame=(yes|no)
Enable or disable the display of a thin gray frame around the DjVu image.
Keyboard shortcuts are enabled by default.
.TP
.BI links=(yes|no)
Enable or disable hyper-links in the DjVu image.
Hyper-links are enabled by default.
.TP
.BI logo=(yes|no)
Enable or disable the display of the DjVu log while the plug-in
is downloading data.  This is enabled by default.
.TP
.BI page= pagenum
Specify the initial page to be displayed.
Page numbers are numbered from 1.
.TP
.BI zoom= zoomfactor
Specify the initial zoom factor.
Unless the toolbar, pop-up menu and keyboard are disabled,
the user will be able to change the zoom factor.
Legal values for
.I zoomfactor
are shown in the below:
.br
.TS
center,box;
lfI l
lfB l
lfB l
lfB l
lfB l
.
number	Magnification factor in range 10% to 999%.
one2one	Select the "one-to-one" mode.
width	Select the "fit width" mode.
page	Select the "fit page" mode.
stretch	Stretch the image to the plugin window size.
.TE
.PP
.TP
.BI mode= modespec
Specify the initial display mode.
Unless the toolbar and pop-up menu are disabled,
the user will be able to change it.
Legal values for
.I modespec
are shown in the below:
.br
.TS
center,box;
lfB l
lfB l
lfB l
lfB l
.
color	Display the color image.
bw	Display the foreground mask only.
fore	Display the foreground only.
back	Display the background only.
.TE
.PP
.TP
.BI hor_align= keyword
Specify the horizontal position of the page in the viewer window.
(This does not specify what part of the page will be shown, but rather
how margins will be laid out around the page in the plugin window.)
Argument
.I keyword
must be
.BR left ,
.BR center ,
or
.BR right .
.TP
.BI ver_align= keyword
Specify the vertical position of the page in the viewer window.
(This does not specify what part of the page will be shown, but rather
how margins will be laid out around the page in the plugin window.)
Argument
.I keyword
must be
.BR top ,
.BR center ,
or
.BR bottom .
.TP
.BI toolbar= keyword {(,|+|-) keyword }
Controls the appearance and the contents of the toolbar.
The argument of option
.B toolbar
is composed of a number of keywords separated
by characters comma, plus or minus.
The appearance of the toolbar is controlled by keywords
placed before the first occurrence of a character plus
or minus. The following keywords are recognized in
this context:
.br
.TS
center,box;
lfB l
lfB l
lfB l
lfB l
lfB l
.
no	Disable toolbar.
always	Disable toolbar "autohide" mode.
auto	Enable toolbar "autohide" mode.
top	Place toolbar along top edge (not implemented).
bottom	Place toolbar along bottom edge.
.TE
.IP ""
The contents of the toolbar is controlled by keywords
placed after the first occurrence of a
character plus or minus.
Each keyword adds (after a plus) or remove (after a minus)
a particular toolbar button or group of buttons.
The initial content of the toolbar is determined
by the first occurrence of a character plus or minus.
When this is a plus
the toolbar is initially empty.
When this is a minus
the toolbar is initially full.
The following keywords are recognized:
.br
.TS
center,box;
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
lfB l
.
fore,back,color,bw	for the display mode selection tool.
rescombo	for the zoom selection tool.
zoom	for the zoom buttons.
pan	for the panning mode button.
zoomsel	for the zooming mode button.
textsel	for the text selection mode button.
rotate	for the image rotation buttons.
search	for the text search button.
save	for the save button.
print	for the print button.
pagecombo	for the page selection tool.
firstlast	for the first-page and last-page buttons.
prevnext	for the previous- and next-page buttons.
backforw	for the back and forward buttons.
.TE
.PP
.TP
.BI highlight= x , y , w , h [, color ]
Display a highlighted rectangle at the specified coordinates and with the
specified color.  Coordinates
.IR x ", " y ", " w ", and " h
are measured in document image coordinates (not screen coordinates).
The origin is set at the bottom left corner of the image.  The color
.I color
must be given in hexadecimal
.SM RRGGBB
format.
Omitting the color argument means to use
.SM XOR
highlighting.  Multiple highlighted zone can be specified.
.TP
.BI rotate=(0|90|180|270)
Rotate the djvu image by the specified angle expressed
in degrees counter-clockwise.
.TP
.BI print=(yes|no)
Enable or disable printing the djvu image.
Printing is enabled by default.
.TP
.BI cache=(yes|no)
Enable or disable the caching of fully decoded pages of the document.
Caching is on by default.  Caching of documents whose
.SM URL
does not contain extension
.BR .djvu " or " .djv
is off by default.
.PP
The same options can be specified as parameters of 
.SM EMBED
or
.SM OBJECT
tags in a
.SM HTML
file.
See
.BR nsdejavu (1)
for more details.




.SH CREDITS
This program was written by Andrei Erofeev <andrew_erofeev@yahoo.com>
and was then improved by Bill Riemers <docbill@sourceforge.net> and
L\('eon Bottou <leonb@users.sourceforge.net>.

.SH SEE ALSO
.BR djvu (1),
.BR ddjvu (1),
.BR nsdejavu (1)
