nsdejavu.o: nsdejavu.c ../../config.h ../../gui/npsdk/npapi.h \
  ../../gui/npsdk/jri.h ../../gui/npsdk/jritypes.h \
  ../../gui/npsdk/jri_md.h ../../gui/npsdk/npunix.c \
  ../../gui/npsdk/npapi.h ../../gui/npsdk/npupp.h
