.\" Copyright (c) 2002 Bill C. Riemers
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVUTOXML 1 "11/15/2002" "DjVuLibre-3.5" "DjVuLibre-3.5"
.de SS
.SH \\0\\0\\0\\$*
..
.SH NAME
djvutoxml \- Extract the hidden text and annotations from DjVu documents in Extensible Markup Language (XML).

.SH SYNOPSIS
.BI "djvutoxml [--page " "pagenum" "] [--with-text|--without-text] [-with-anno|--without-anno]  " "inputdjvufile" " [" outputxmlfile "]"

.SH DESCRIPTION
Program 
.B djvutoxml
decodes the hidden text layer and annotation layer of a DjVu document 
.I inputdjvufile 
and prints the 
.SM UTF8 
encoded Extensible Markup Language
.SM (XML) 
file 
.I outputxmlfile 
or the standard output into file 
.I outputxmlfile
or the standard output.   The hidden text layer is usually generated with the help of optical character recognition software, and the annotation layer is usually created with a commercial visual editor.

The precise format of the XML output is defined in the pubtext/DjVuXML-s.dtd file.  See 
.I djvuxml-s (3)
for more details.

.SH OPTIONS
.TP
.BI "--page " "pagenum"
Select a page in a multi-page document.
Without this option, 
.B djvutoxml
outputs the 
.SM XML 
corresponding to all pages of the document.

.TP 
.BI "--with-text"
Specifies the 
.SM HIDDENTEXT 
element for each page should be included in the output.  If specified without the
.I –with-anno
flag then the
.I –without-anno 
is implied.  If none of the  
.I --with-text, 
.I --without-text, 
.I --with-anno, 
or
.I --without-anno, 
flags are specified, then the  
.I --with-text 
and 
.I --with-anno 
flags are implied.

.TP
.BI "--without-text"
Specifies not to output the 
.SM HIDDENTEXT 
element for each page.  If specified without the 
.I –without-anno 
flag then the 
.I –with-anno 
flag is implied.

.TP
.BI "--with-anno"
Specifies the area 
.SM MAP 
element for each page should be included in the output.  If specified without the
.I –with-text 
flag then the
.I –without-text 
flag is implied.

.TP
.BI "--without-anno"
Specifies the area 
.SM MAP 
element for each page should not be included in the output.  If specified without the
.I –without-text 
flag then the
.I –with-text 
flag is implied.

.SH REMARKS
Use with 
.BR djvuxmlparser (1)
to modify the contents of a DjVu file.

.SH CREDITS
This program was written by Bill C. Riemers <docbill@sourceforge.net>.

.SH SEE ALSO
.BR djvu (1),
.BR djvuxmlparser (1),
.BR djvused (1),
.BR djvutxt (1),
.BR djvuxml-s (3),
.BR xml2native (1),
.BR xml2utf8 (1),
.BR xml2utf16 (1),
and
.BR utf8 (3).

