djvutoxml.o: djvutoxml.cpp ../config.h ../libdjvu/DjVuDocument.h \
  ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GURL.h ../libdjvu/GString.h \
  ../libdjvu/GContainer.h ../libdjvu/GSmartPointer.h ../libdjvu/atomic.h \
  ../libdjvu/Arrays.h ../libdjvu/GOS.h ../libdjvu/DjVuMessage.h \
  ../libdjvu/DjVuMessageLite.h ../libdjvu/ByteStream.h \
  ../libdjvu/DjVuAnno.h ../libdjvu/DjVuText.h ../libdjvu/GMapAreas.h \
  ../libdjvu/GRect.h ../libdjvu/DjVuImage.h ../libdjvu/DjVuFile.h \
  ../libdjvu/DjVuInfo.h ../libdjvu/DjVuPalette.h ../libdjvu/GPixmap.h \
  ../libdjvu/DjVuAnno.h ../libdjvu/debug.h
djvuxmlparser.o: djvuxmlparser.cpp ../config.h ../libdjvu/XMLParser.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/atomic.h ../libdjvu/GURL.h \
  ../libdjvu/GString.h ../libdjvu/Arrays.h ../libdjvu/GThreads.h \
  ../libdjvu/XMLTags.h ../libdjvu/GOS.h ../libdjvu/GURL.h \
  ../libdjvu/DjVuDocument.h ../libdjvu/DjVuPort.h ../libdjvu/ByteStream.h \
  ../libdjvu/DjVuMessage.h ../libdjvu/DjVuMessageLite.h
