#! /bin/sh

case "$1" in
    configure)

	# Register menu entries (non debian menus)
	if [ -x /usr/bin/update-desktop-database ] ; then
	    /usr/bin/update-desktop-database
	fi

	# Alternatives
	if [ -x /usr/sbin/update-alternatives ] ; then
	    update-alternatives --quiet \
		--install /usr/bin/djview djview /usr/bin/djview3 103 \
		--slave \
		/usr/share/man/man1/djview.1.gz djview.1.gz \
		/usr/share/man/man1/djview3.1.gz
	fi
	;;
esac

#DEBHELPER#
