#!/bin/sh

# Step 1 -- locate the directory containing this script

progname="`basename $0`"
if [ "$progname" != "$0" ]
then
    # programname contains directory components
    progdir="`dirname $0`"
else
    # must search along path
    tmpvar="$PATH"
    while [ -n "$tmpvar" ]
    do
      IFS=':' read progdir tmpvar <<EOF
$tmpvar
EOF
      test -x "$progdir/$progname" && break
    done
fi
progdir=`cd $progdir ; pwd`
while [ -L "$progdir/$progname" ]
do
    tmpvar=`ls -ld $progdir/$progname`
    tmpvar=`expr "$tmpvar" : '.*-> *\(.*\)'`
    progname=`basename $tmpvar` 
    tmpvar=`dirname $tmpvar` 
    progdir=`cd $progdir ; cd $tmpvar ; pwd` 
done
if [ ! -x "$progdir/$progname" ]
then
   echo 1>&2 "$progname: command not found"
   exit 10
fi

# Step 2 -- execute ghostscript

gsdir="$progdir"
GS_LIB="$gsdir/lib:$gsdir/fonts" exec "$gsdir/bin/gs" "$@"
