Arrays.lo: ./Arrays.cpp ../config.h Arrays.h GException.h DjVuGlobal.h \
  GSmartPointer.h ByteStream.h
BSByteStream.lo: ./BSByteStream.cpp ../config.h BSByteStream.h \
  ByteStream.h Arrays.h GException.h DjVuGlobal.h GSmartPointer.h \
  ZPCodec.h GContainer.h
BSEncodeByteStream.lo: ./BSEncodeByteStream.cpp ../config.h BSByteStream.h \
  ByteStream.h Arrays.h GException.h DjVuGlobal.h GSmartPointer.h \
  ZPCodec.h GContainer.h GString.h
ByteStream.lo: ./ByteStream.cpp ../config.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h GOS.h GString.h GContainer.h \
  GURL.h GThreads.h DjVuMessage.h DjVuMessageLite.h
DataPool.lo: ./DataPool.cpp ../config.h DataPool.h GThreads.h DjVuGlobal.h \
  GException.h GString.h GContainer.h GSmartPointer.h GURL.h Arrays.h \
  IFFByteStream.h ByteStream.h GOS.h debug.h
ddjvuapi.lo: ./ddjvuapi.cpp ../config.h GException.h DjVuGlobal.h \
  GSmartPointer.h GThreads.h GContainer.h ByteStream.h Arrays.h \
  IFFByteStream.h GString.h GBitmap.h GPixmap.h GScaler.h GRect.h \
  DjVuPort.h GURL.h DataPool.h DjVuInfo.h IW44Image.h ZPCodec.h \
  DjVuImage.h DjVuFile.h DjVuPalette.h DjVuAnno.h DjVuFileCache.h \
  DjVuDocument.h DjVuMessageLite.h DjVuMessage.h DjVmNav.h DjVuText.h \
  GMapAreas.h ddjvuapi.h
debug.lo: ./debug.cpp ../config.h debug.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h ByteStream.h Arrays.h GURL.h \
  GThreads.h
DjVmDir0.lo: ./DjVmDir0.cpp ../config.h DjVmDir0.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h ByteStream.h Arrays.h debug.h
DjVmDir.lo: ./DjVmDir.cpp ../config.h DjVmDir.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h GThreads.h BSByteStream.h \
  ByteStream.h Arrays.h ZPCodec.h GURL.h debug.h
DjVmDoc.lo: ./DjVmDoc.cpp ../config.h DjVmDoc.h DjVmDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h GThreads.h \
  DjVmNav.h DataPool.h GURL.h Arrays.h IFFByteStream.h ByteStream.h GOS.h \
  debug.h
DjVmNav.lo: ./DjVmNav.cpp ../config.h DjVuDocument.h DjVuPort.h GThreads.h \
  DjVuGlobal.h GException.h GURL.h GString.h GContainer.h GSmartPointer.h \
  Arrays.h DjVmNav.h BSByteStream.h ByteStream.h ZPCodec.h debug.h
DjVuAnno.lo: ./DjVuAnno.cpp ../config.h DjVuAnno.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h IFFByteStream.h ByteStream.h \
  Arrays.h BSByteStream.h ZPCodec.h GMapAreas.h GRect.h GURL.h GThreads.h \
  debug.h
DjVuDocEditor.lo: ./DjVuDocEditor.cpp ../config.h DjVuDocEditor.h \
  DjVuDocument.h DjVuPort.h GThreads.h DjVuGlobal.h GException.h GURL.h \
  GString.h GContainer.h GSmartPointer.h Arrays.h DjVmDoc.h DjVmDir.h \
  DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h GPixmap.h \
  DjVuAnno.h IFFByteStream.h ByteStream.h DataPool.h IW44Image.h \
  ZPCodec.h GOS.h DjVmNav.h debug.h
DjVuDocument.lo: ./DjVuDocument.cpp ../config.h DjVuDocument.h DjVuPort.h \
  GThreads.h DjVuGlobal.h GException.h GURL.h GString.h GContainer.h \
  GSmartPointer.h Arrays.h DjVmDoc.h DjVmDir.h DjVmDir0.h DjVmNav.h \
  DjVuNavDir.h DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h \
  GPixmap.h DjVuAnno.h DjVuFileCache.h IFFByteStream.h ByteStream.h GOS.h \
  DataPool.h IW44Image.h ZPCodec.h debug.h
DjVuDumpHelper.lo: ./DjVuDumpHelper.cpp ../config.h DjVuDumpHelper.h \
  GSmartPointer.h DjVuGlobal.h DataPool.h GThreads.h GException.h \
  GString.h GContainer.h GURL.h Arrays.h DjVmDir.h DjVuInfo.h GRect.h \
  IFFByteStream.h ByteStream.h
DjVuErrorList.lo: ./DjVuErrorList.cpp ../config.h DjVuErrorList.h \
  DjVuPort.h GThreads.h DjVuGlobal.h GException.h GURL.h GString.h \
  GContainer.h GSmartPointer.h Arrays.h DjVmDoc.h DjVmDir.h GOS.h \
  DataPool.h
DjVuFileCache.lo: ./DjVuFileCache.cpp ../config.h DjVuFileCache.h \
  DjVuFile.h DjVuInfo.h GSmartPointer.h DjVuGlobal.h GRect.h \
  DjVuPalette.h GContainer.h GException.h GPixmap.h DjVuPort.h GThreads.h \
  GURL.h GString.h Arrays.h debug.h
DjVuFile.lo: ./DjVuFile.cpp ../config.h DjVuFile.h DjVuInfo.h \
  GSmartPointer.h DjVuGlobal.h GRect.h DjVuPalette.h GContainer.h \
  GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h GString.h Arrays.h \
  IFFByteStream.h ByteStream.h GOS.h MMRDecoder.h JPEGDecoder.h \
  DjVuAnno.h DjVuText.h GMapAreas.h DataPool.h JB2Image.h ZPCodec.h \
  IW44Image.h DjVuNavDir.h BSByteStream.h debug.h
DjVuGlobal.lo: ./DjVuGlobal.cpp ../config.h
DjVuGlobalMemory.lo: ./DjVuGlobalMemory.cpp ../config.h
DjVuImage.lo: ./DjVuImage.cpp ../config.h DjVuImage.h DjVuFile.h \
  DjVuInfo.h GSmartPointer.h DjVuGlobal.h GRect.h DjVuPalette.h \
  GContainer.h GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h \
  GString.h Arrays.h DjVuAnno.h GScaler.h GBitmap.h DjVuDocument.h \
  JB2Image.h ZPCodec.h IW44Image.h DataPool.h ByteStream.h GMapAreas.h \
  DjVuText.h IFFByteStream.h BSByteStream.h debug.h
DjVuInfo.lo: ./DjVuInfo.cpp ../config.h DjVuInfo.h GSmartPointer.h \
  DjVuGlobal.h GRect.h GException.h ByteStream.h Arrays.h GString.h \
  GContainer.h
DjVuMessage.lo: ./DjVuMessage.cpp ../config.h DjVuMessage.h \
  DjVuMessageLite.h GString.h DjVuGlobal.h GContainer.h GException.h \
  GSmartPointer.h GOS.h XMLTags.h ByteStream.h Arrays.h GURL.h GThreads.h \
  debug.h
DjVuMessageLite.lo: ./DjVuMessageLite.cpp ../config.h DjVuMessageLite.h \
  GString.h DjVuGlobal.h GContainer.h GException.h GSmartPointer.h GOS.h \
  XMLTags.h ByteStream.h Arrays.h GURL.h GThreads.h debug.h
DjVuNavDir.lo: ./DjVuNavDir.cpp ../config.h DjVuNavDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h GThreads.h \
  GURL.h Arrays.h debug.h GOS.h ByteStream.h
DjVuPalette.lo: ./DjVuPalette.cpp ../config.h GException.h DjVuGlobal.h \
  ByteStream.h Arrays.h GSmartPointer.h BSByteStream.h ZPCodec.h \
  GContainer.h DjVuPalette.h GPixmap.h
DjVuPort.lo: ./DjVuPort.cpp ../config.h DjVuPort.h GThreads.h DjVuGlobal.h \
  GException.h GURL.h GString.h GContainer.h GSmartPointer.h Arrays.h \
  GOS.h DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h GPixmap.h \
  DjVuAnno.h DjVuDocument.h DjVuMessageLite.h DataPool.h
DjVuText.lo: ./DjVuText.cpp ../config.h DjVuText.h GMapAreas.h \
  GSmartPointer.h DjVuGlobal.h GContainer.h GException.h GString.h \
  GRect.h GURL.h Arrays.h GThreads.h IFFByteStream.h ByteStream.h \
  BSByteStream.h ZPCodec.h debug.h
DjVuToPS.lo: ./DjVuToPS.cpp ../config.h DjVuToPS.h DjVuGlobal.h GRect.h \
  DjVuDocument.h DjVuPort.h GThreads.h GException.h GURL.h GString.h \
  GContainer.h GSmartPointer.h Arrays.h DjVuText.h GMapAreas.h \
  IFFByteStream.h ByteStream.h BSByteStream.h ZPCodec.h DjVuImage.h \
  DjVuFile.h DjVuInfo.h DjVuPalette.h GPixmap.h DjVuAnno.h DataPool.h \
  IW44Image.h JB2Image.h GBitmap.h debug.h
GBitmap.lo: ./GBitmap.cpp ../config.h GBitmap.h GSmartPointer.h \
  DjVuGlobal.h ByteStream.h Arrays.h GException.h GRect.h GString.h \
  GContainer.h GThreads.h
GContainer.lo: ./GContainer.cpp ../config.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h
GException.lo: ./GException.cpp ../config.h GException.h DjVuGlobal.h \
  DjVuMessageLite.h GString.h GContainer.h GSmartPointer.h debug.h
GIFFManager.lo: ./GIFFManager.cpp ../config.h GIFFManager.h \
  IFFByteStream.h DjVuGlobal.h GException.h GString.h GContainer.h \
  GSmartPointer.h ByteStream.h Arrays.h debug.h
GMapAreas.lo: ./GMapAreas.cpp ../config.h GMapAreas.h GSmartPointer.h \
  DjVuGlobal.h GContainer.h GException.h GString.h GRect.h GURL.h \
  Arrays.h GThreads.h debug.h
GOS.lo: ./GOS.cpp ../config.h GException.h DjVuGlobal.h GThreads.h GOS.h \
  GString.h GContainer.h GSmartPointer.h GURL.h Arrays.h
GPixmap.lo: ./GPixmap.cpp ../config.h GPixmap.h GSmartPointer.h \
  DjVuGlobal.h GString.h GContainer.h GException.h ByteStream.h Arrays.h \
  GRect.h GBitmap.h GThreads.h JPEGDecoder.h
GRect.lo: ./GRect.cpp ../config.h GRect.h DjVuGlobal.h GException.h
GScaler.lo: ./GScaler.cpp ../config.h GScaler.h GException.h DjVuGlobal.h \
  GRect.h GBitmap.h GSmartPointer.h GPixmap.h
GSmartPointer.lo: ./GSmartPointer.cpp ../config.h GThreads.h DjVuGlobal.h \
  GException.h GSmartPointer.h
GString.lo: ./GString.cpp ../config.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h GThreads.h debug.h
GThreads.lo: ./GThreads.cpp ../config.h GThreads.h DjVuGlobal.h \
  GException.h DjVuMessageLite.h GString.h GContainer.h GSmartPointer.h
GUnicode.lo: ./GUnicode.cpp ../config.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h
GURL.lo: ./GURL.cpp ../config.h GException.h DjVuGlobal.h GOS.h GString.h \
  GContainer.h GSmartPointer.h GURL.h Arrays.h GThreads.h debug.h
IFFByteStream.lo: ./IFFByteStream.cpp ../config.h IFFByteStream.h \
  DjVuGlobal.h GException.h GString.h GContainer.h GSmartPointer.h \
  ByteStream.h Arrays.h
IW44EncodeCodec.lo: ./IW44EncodeCodec.cpp ../config.h IW44Image.h \
  GSmartPointer.h DjVuGlobal.h ZPCodec.h GContainer.h GException.h \
  GBitmap.h GPixmap.h IFFByteStream.h GString.h ByteStream.h Arrays.h \
  GRect.h MMX.h
IW44Image.lo: ./IW44Image.cpp ../config.h IW44Image.h GSmartPointer.h \
  DjVuGlobal.h ZPCodec.h GContainer.h GException.h GBitmap.h GPixmap.h \
  IFFByteStream.h GString.h ByteStream.h Arrays.h GRect.h MMX.h
JB2EncodeCodec.lo: ./JB2EncodeCodec.cpp ../config.h JB2Image.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h ZPCodec.h \
  GBitmap.h
JB2Image.lo: ./JB2Image.cpp ../config.h JB2Image.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h ZPCodec.h GThreads.h GRect.h \
  GBitmap.h
JPEGDecoder.lo: ./JPEGDecoder.cpp ../config.h JPEGDecoder.h \
  GSmartPointer.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h GPixmap.h
MMRDecoder.lo: ./MMRDecoder.cpp ../config.h MMRDecoder.h GSmartPointer.h \
  DjVuGlobal.h JB2Image.h GString.h GContainer.h GException.h ZPCodec.h \
  ByteStream.h Arrays.h GBitmap.h
MMX.lo: ./MMX.cpp ../config.h MMX.h DjVuGlobal.h
UnicodeByteStream.lo: ./UnicodeByteStream.cpp ../config.h \
  UnicodeByteStream.h DjVuGlobal.h GString.h GContainer.h GException.h \
  GSmartPointer.h ByteStream.h Arrays.h
XMLParser.lo: ./XMLParser.cpp ../config.h XMLParser.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h GURL.h GString.h Arrays.h \
  GThreads.h XMLTags.h ByteStream.h GOS.h DjVuDocument.h DjVuPort.h \
  DjVuText.h GMapAreas.h GRect.h DjVuAnno.h DjVuFile.h DjVuInfo.h \
  DjVuPalette.h GPixmap.h DjVuImage.h debug.h
XMLTags.lo: ./XMLTags.cpp ../config.h XMLTags.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h GString.h UnicodeByteStream.h ByteStream.h \
  Arrays.h
ZPCodec.lo: ./ZPCodec.cpp ../config.h ZPCodec.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h ByteStream.h Arrays.h
