Arrays.lo Arrays.o: Arrays.cpp ../config.h Arrays.h GException.h DjVuGlobal.h \
  GSmartPointer.h DjVuGlobal.h GException.h ByteStream.h Arrays.h
BSByteStream.lo BSByteStream.o: BSByteStream.cpp ../config.h BSByteStream.h ByteStream.h \
  Arrays.h GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h \
  GException.h ZPCodec.h GContainer.h GException.h GSmartPointer.h
BSEncodeByteStream.lo BSEncodeByteStream.o: BSEncodeByteStream.cpp ../config.h BSByteStream.h \
  ByteStream.h Arrays.h GException.h DjVuGlobal.h GSmartPointer.h \
  DjVuGlobal.h GException.h ZPCodec.h GContainer.h GException.h \
  GSmartPointer.h GString.h DjVuGlobal.h GContainer.h
ByteStream.lo ByteStream.o: ByteStream.cpp ../config.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h GOS.h \
  DjVuGlobal.h GString.h DjVuGlobal.h GContainer.h GException.h \
  GSmartPointer.h GURL.h GString.h Arrays.h GThreads.h DjVuGlobal.h \
  GException.h DjVuMessage.h DjVuMessageLite.h GString.h
DataPool.lo DataPool.o: DataPool.cpp ../config.h DataPool.h GThreads.h DjVuGlobal.h \
  GException.h DjVuGlobal.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h DjVuGlobal.h GURL.h GString.h Arrays.h \
  GException.h GSmartPointer.h GThreads.h IFFByteStream.h DjVuGlobal.h \
  GException.h GString.h ByteStream.h Arrays.h GString.h GOS.h \
  DjVuGlobal.h GString.h GURL.h debug.h
DjVmDir.lo DjVmDir.o: DjVmDir.cpp ../config.h DjVmDir.h GString.h DjVuGlobal.h \
  GContainer.h GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h \
  GThreads.h DjVuGlobal.h GException.h BSByteStream.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h GException.h ZPCodec.h \
  GContainer.h GURL.h GString.h Arrays.h GThreads.h debug.h
DjVmDir0.lo DjVmDir0.o: DjVmDir0.cpp ../config.h DjVmDir0.h GString.h DjVuGlobal.h \
  GContainer.h GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h \
  ByteStream.h Arrays.h GException.h GSmartPointer.h debug.h
DjVmDoc.lo DjVmDoc.o: DjVmDoc.cpp ../config.h DjVmDoc.h DjVmDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h DjVuGlobal.h GSmartPointer.h \
  DjVuGlobal.h GThreads.h DjVuGlobal.h GException.h DjVmNav.h \
  DjVuGlobal.h GString.h GThreads.h DataPool.h GThreads.h GString.h \
  GURL.h GString.h Arrays.h GException.h GSmartPointer.h GThreads.h \
  IFFByteStream.h DjVuGlobal.h GException.h GString.h ByteStream.h \
  Arrays.h GOS.h DjVuGlobal.h GString.h debug.h
DjVmNav.lo DjVmNav.o: DjVmNav.cpp ../config.h DjVuDocument.h DjVuPort.h GThreads.h \
  DjVuGlobal.h GException.h DjVuGlobal.h GURL.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h DjVuGlobal.h Arrays.h \
  GException.h GSmartPointer.h GThreads.h DjVmNav.h DjVuGlobal.h \
  GString.h GThreads.h BSByteStream.h ByteStream.h Arrays.h GException.h \
  ZPCodec.h GContainer.h GURL.h debug.h
DjVuAnno.lo DjVuAnno.o: DjVuAnno.cpp ../config.h DjVuAnno.h GString.h DjVuGlobal.h \
  GContainer.h GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h \
  GContainer.h GException.h IFFByteStream.h DjVuGlobal.h GException.h \
  GString.h ByteStream.h Arrays.h GException.h GSmartPointer.h \
  BSByteStream.h ByteStream.h GException.h ZPCodec.h GContainer.h \
  GMapAreas.h GSmartPointer.h GContainer.h GString.h GRect.h DjVuGlobal.h \
  GURL.h GString.h Arrays.h GThreads.h DjVuGlobal.h GException.h debug.h
DjVuDocEditor.lo DjVuDocEditor.o: DjVuDocEditor.cpp ../config.h DjVuDocEditor.h \
  DjVuDocument.h DjVuPort.h GThreads.h DjVuGlobal.h GException.h \
  DjVuGlobal.h GURL.h GString.h DjVuGlobal.h GContainer.h GException.h \
  GSmartPointer.h DjVuGlobal.h Arrays.h GException.h GSmartPointer.h \
  GThreads.h DjVmDoc.h DjVmDir.h GString.h GThreads.h DjVuImage.h \
  DjVuFile.h DjVuInfo.h GSmartPointer.h GRect.h DjVuGlobal.h \
  DjVuPalette.h GContainer.h GPixmap.h GSmartPointer.h DjVuPort.h \
  DjVuAnno.h GString.h GRect.h IFFByteStream.h DjVuGlobal.h GException.h \
  GString.h ByteStream.h Arrays.h DataPool.h GThreads.h GString.h GURL.h \
  IW44Image.h GSmartPointer.h ZPCodec.h GContainer.h GOS.h DjVuGlobal.h \
  GString.h GURL.h DjVuAnno.h GRect.h DjVmNav.h DjVuGlobal.h GString.h \
  GThreads.h debug.h
DjVuDocument.lo DjVuDocument.o: DjVuDocument.cpp ../config.h DjVuDocument.h DjVuPort.h \
  GThreads.h DjVuGlobal.h GException.h DjVuGlobal.h GURL.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h DjVuGlobal.h \
  Arrays.h GException.h GSmartPointer.h GThreads.h DjVmDoc.h DjVmDir.h \
  GString.h GThreads.h DjVmDir0.h GString.h DjVmNav.h DjVuGlobal.h \
  GString.h GThreads.h DjVuNavDir.h GString.h GThreads.h GURL.h \
  DjVuImage.h DjVuFile.h DjVuInfo.h GSmartPointer.h GRect.h DjVuGlobal.h \
  DjVuPalette.h GContainer.h GPixmap.h GSmartPointer.h DjVuPort.h \
  DjVuAnno.h GString.h GRect.h DjVuFileCache.h DjVuFile.h IFFByteStream.h \
  DjVuGlobal.h GException.h GString.h ByteStream.h Arrays.h GOS.h \
  DjVuGlobal.h GString.h DataPool.h GThreads.h GString.h GURL.h \
  IW44Image.h GSmartPointer.h ZPCodec.h GContainer.h GRect.h debug.h
DjVuDumpHelper.lo DjVuDumpHelper.o: DjVuDumpHelper.cpp ../config.h DjVuDumpHelper.h \
  GSmartPointer.h DjVuGlobal.h DataPool.h GThreads.h DjVuGlobal.h \
  GException.h DjVuGlobal.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h GURL.h GString.h Arrays.h GException.h \
  GSmartPointer.h GThreads.h DjVmDir.h GString.h GThreads.h DjVuInfo.h \
  GSmartPointer.h GRect.h DjVuGlobal.h IFFByteStream.h DjVuGlobal.h \
  GException.h GString.h ByteStream.h Arrays.h
DjVuErrorList.lo DjVuErrorList.o: DjVuErrorList.cpp ../config.h DjVuErrorList.h DjVuPort.h \
  GThreads.h DjVuGlobal.h GException.h DjVuGlobal.h GURL.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h DjVuGlobal.h \
  Arrays.h GException.h GSmartPointer.h GThreads.h DjVmDoc.h DjVmDir.h \
  GString.h GThreads.h GException.h GContainer.h GOS.h DjVuGlobal.h \
  GString.h DataPool.h GThreads.h GString.h GURL.h
DjVuFile.lo DjVuFile.o: DjVuFile.cpp ../config.h DjVuFile.h DjVuInfo.h \
  GSmartPointer.h DjVuGlobal.h GRect.h DjVuGlobal.h DjVuPalette.h \
  GContainer.h GException.h DjVuGlobal.h GSmartPointer.h GPixmap.h \
  GSmartPointer.h DjVuPort.h GThreads.h DjVuGlobal.h GException.h GURL.h \
  GString.h DjVuGlobal.h GContainer.h Arrays.h GException.h \
  GSmartPointer.h GThreads.h IFFByteStream.h DjVuGlobal.h GException.h \
  GString.h ByteStream.h Arrays.h GOS.h DjVuGlobal.h GString.h \
  MMRDecoder.h GSmartPointer.h JPEGDecoder.h GSmartPointer.h DjVuAnno.h \
  GString.h DjVuText.h GMapAreas.h GSmartPointer.h GContainer.h GString.h \
  GRect.h GURL.h DataPool.h GThreads.h GString.h GURL.h JB2Image.h \
  GString.h ZPCodec.h GContainer.h IW44Image.h GSmartPointer.h ZPCodec.h \
  DjVuNavDir.h GString.h GThreads.h GURL.h BSByteStream.h ByteStream.h \
  GException.h ZPCodec.h debug.h
DjVuFileCache.lo DjVuFileCache.o: DjVuFileCache.cpp ../config.h DjVuFileCache.h DjVuFile.h \
  DjVuInfo.h GSmartPointer.h DjVuGlobal.h GRect.h DjVuGlobal.h \
  DjVuPalette.h GContainer.h GException.h DjVuGlobal.h GSmartPointer.h \
  GPixmap.h GSmartPointer.h DjVuPort.h GThreads.h DjVuGlobal.h \
  GException.h GURL.h GString.h DjVuGlobal.h GContainer.h Arrays.h \
  GException.h GSmartPointer.h GThreads.h debug.h
DjVuGlobal.lo DjVuGlobal.o: DjVuGlobal.cpp ../config.h
DjVuGlobalMemory.lo DjVuGlobalMemory.o: DjVuGlobalMemory.cpp ../config.h
DjVuImage.lo DjVuImage.o: DjVuImage.cpp ../config.h DjVuImage.h DjVuFile.h DjVuInfo.h \
  GSmartPointer.h DjVuGlobal.h GRect.h DjVuGlobal.h DjVuPalette.h \
  GContainer.h GException.h DjVuGlobal.h GSmartPointer.h GPixmap.h \
  GSmartPointer.h DjVuPort.h GThreads.h DjVuGlobal.h GException.h GURL.h \
  GString.h DjVuGlobal.h GContainer.h Arrays.h GException.h \
  GSmartPointer.h GThreads.h DjVuAnno.h GString.h GRect.h GScaler.h \
  GException.h GRect.h GBitmap.h GSmartPointer.h GPixmap.h DjVuDocument.h \
  DjVuPort.h DjVuPalette.h GContainer.h GSmartPointer.h JB2Image.h \
  GString.h ZPCodec.h GContainer.h IW44Image.h GSmartPointer.h ZPCodec.h \
  DataPool.h GThreads.h GString.h GURL.h ByteStream.h Arrays.h \
  GMapAreas.h GSmartPointer.h GContainer.h GString.h GRect.h GURL.h \
  DjVuText.h GMapAreas.h IFFByteStream.h DjVuGlobal.h GException.h \
  GString.h ByteStream.h BSByteStream.h ByteStream.h GException.h \
  ZPCodec.h debug.h
DjVuInfo.lo DjVuInfo.o: DjVuInfo.cpp ../config.h DjVuInfo.h GSmartPointer.h \
  DjVuGlobal.h GRect.h DjVuGlobal.h GException.h DjVuGlobal.h \
  ByteStream.h Arrays.h GException.h GSmartPointer.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h
DjVuMessage.lo DjVuMessage.o: DjVuMessage.cpp ../config.h DjVuMessage.h \
  DjVuMessageLite.h GString.h DjVuGlobal.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h DjVuGlobal.h GOS.h DjVuGlobal.h GString.h \
  XMLTags.h GContainer.h GString.h ByteStream.h Arrays.h GException.h \
  GSmartPointer.h GURL.h GString.h Arrays.h GThreads.h DjVuGlobal.h \
  GException.h debug.h
DjVuMessageLite.lo DjVuMessageLite.o: DjVuMessageLite.cpp ../config.h DjVuMessageLite.h \
  GString.h DjVuGlobal.h GContainer.h GException.h DjVuGlobal.h \
  GSmartPointer.h DjVuGlobal.h GOS.h DjVuGlobal.h GString.h XMLTags.h \
  GContainer.h GString.h ByteStream.h Arrays.h GException.h \
  GSmartPointer.h GURL.h GString.h Arrays.h GThreads.h DjVuGlobal.h \
  GException.h debug.h
DjVuNavDir.lo DjVuNavDir.o: DjVuNavDir.cpp ../config.h DjVuNavDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h DjVuGlobal.h GSmartPointer.h \
  DjVuGlobal.h GThreads.h DjVuGlobal.h GException.h GURL.h GString.h \
  Arrays.h GException.h GSmartPointer.h GThreads.h debug.h GException.h \
  GOS.h DjVuGlobal.h GString.h ByteStream.h Arrays.h GURL.h
DjVuPalette.lo DjVuPalette.o: DjVuPalette.cpp ../config.h GException.h DjVuGlobal.h \
  ByteStream.h Arrays.h GException.h GSmartPointer.h DjVuGlobal.h \
  BSByteStream.h ByteStream.h GException.h ZPCodec.h GContainer.h \
  GException.h GSmartPointer.h DjVuPalette.h GContainer.h GPixmap.h \
  GSmartPointer.h
DjVuPort.lo DjVuPort.o: DjVuPort.cpp ../config.h DjVuPort.h GThreads.h DjVuGlobal.h \
  GException.h DjVuGlobal.h GURL.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h DjVuGlobal.h Arrays.h GException.h \
  GSmartPointer.h GThreads.h GOS.h DjVuGlobal.h GString.h DjVuImage.h \
  DjVuFile.h DjVuInfo.h GSmartPointer.h GRect.h DjVuGlobal.h \
  DjVuPalette.h GContainer.h GPixmap.h GSmartPointer.h DjVuPort.h \
  DjVuAnno.h GString.h GRect.h DjVuDocument.h DjVuPort.h DjVuFile.h \
  DjVuMessageLite.h GString.h DataPool.h GThreads.h GString.h GURL.h
DjVuText.lo DjVuText.o: DjVuText.cpp ../config.h DjVuText.h GMapAreas.h \
  GSmartPointer.h DjVuGlobal.h GContainer.h GException.h DjVuGlobal.h \
  GSmartPointer.h GString.h DjVuGlobal.h GContainer.h GRect.h \
  DjVuGlobal.h GURL.h GString.h Arrays.h GException.h GSmartPointer.h \
  GThreads.h DjVuGlobal.h GException.h IFFByteStream.h DjVuGlobal.h \
  GException.h GString.h ByteStream.h Arrays.h BSByteStream.h \
  ByteStream.h GException.h ZPCodec.h GContainer.h debug.h
DjVuToPS.lo DjVuToPS.o: DjVuToPS.cpp ../config.h DjVuToPS.h DjVuGlobal.h GRect.h \
  DjVuGlobal.h DjVuDocument.h DjVuPort.h GThreads.h DjVuGlobal.h \
  GException.h DjVuGlobal.h GURL.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h DjVuGlobal.h Arrays.h GException.h \
  GSmartPointer.h GThreads.h DjVuText.h GMapAreas.h GSmartPointer.h \
  GContainer.h GString.h GRect.h GURL.h IFFByteStream.h DjVuGlobal.h \
  GException.h GString.h ByteStream.h Arrays.h BSByteStream.h \
  ByteStream.h GException.h ZPCodec.h GContainer.h DjVuImage.h DjVuFile.h \
  DjVuInfo.h GSmartPointer.h GRect.h DjVuPalette.h GContainer.h GPixmap.h \
  GSmartPointer.h DjVuPort.h DjVuAnno.h GString.h GRect.h DjVuText.h \
  DataPool.h GThreads.h GString.h GURL.h IW44Image.h GSmartPointer.h \
  ZPCodec.h JB2Image.h GString.h ZPCodec.h GBitmap.h GSmartPointer.h \
  GPixmap.h debug.h
GBitmap.lo GBitmap.o: GBitmap.cpp ../config.h GBitmap.h GSmartPointer.h DjVuGlobal.h \
  ByteStream.h Arrays.h GException.h DjVuGlobal.h GSmartPointer.h GRect.h \
  DjVuGlobal.h GString.h DjVuGlobal.h GContainer.h GException.h \
  GSmartPointer.h GThreads.h DjVuGlobal.h GException.h GException.h
GContainer.lo GContainer.o: GContainer.cpp ../config.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h DjVuGlobal.h
GException.lo GException.o: GException.cpp ../config.h GException.h DjVuGlobal.h \
  DjVuMessageLite.h GString.h DjVuGlobal.h GContainer.h GException.h \
  GSmartPointer.h DjVuGlobal.h debug.h
GIFFManager.lo GIFFManager.o: GIFFManager.cpp ../config.h GIFFManager.h IFFByteStream.h \
  DjVuGlobal.h GException.h DjVuGlobal.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h GContainer.h Arrays.h \
  GSmartPointer.h GString.h GException.h debug.h
GMapAreas.lo GMapAreas.o: GMapAreas.cpp ../config.h GMapAreas.h GSmartPointer.h \
  DjVuGlobal.h GContainer.h GException.h DjVuGlobal.h GSmartPointer.h \
  GString.h DjVuGlobal.h GContainer.h GRect.h DjVuGlobal.h GURL.h \
  GString.h Arrays.h GException.h GSmartPointer.h GThreads.h DjVuGlobal.h \
  GException.h GException.h debug.h
GOS.lo GOS.o: GOS.cpp ../config.h GException.h DjVuGlobal.h GThreads.h \
  DjVuGlobal.h GException.h GOS.h DjVuGlobal.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h DjVuGlobal.h GURL.h GString.h \
  Arrays.h GException.h GSmartPointer.h GThreads.h
GPixmap.lo GPixmap.o: GPixmap.cpp ../config.h GPixmap.h GSmartPointer.h DjVuGlobal.h \
  GString.h DjVuGlobal.h GContainer.h GException.h DjVuGlobal.h \
  GSmartPointer.h GException.h ByteStream.h Arrays.h GException.h \
  GSmartPointer.h GRect.h DjVuGlobal.h GBitmap.h GSmartPointer.h \
  GThreads.h DjVuGlobal.h GException.h Arrays.h JPEGDecoder.h \
  GSmartPointer.h
GRect.lo GRect.o: GRect.cpp ../config.h GRect.h DjVuGlobal.h GException.h \
  DjVuGlobal.h
GScaler.lo GScaler.o: GScaler.cpp ../config.h GScaler.h GException.h DjVuGlobal.h \
  GRect.h DjVuGlobal.h GBitmap.h GSmartPointer.h DjVuGlobal.h GPixmap.h \
  GSmartPointer.h
GSmartPointer.lo GSmartPointer.o: GSmartPointer.cpp ../config.h GThreads.h DjVuGlobal.h \
  GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h GException.h \
  atomic.h
GString.lo GString.o: GString.cpp ../config.h GString.h DjVuGlobal.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h GThreads.h \
  DjVuGlobal.h GException.h debug.h
GThreads.lo GThreads.o: GThreads.cpp ../config.h GThreads.h DjVuGlobal.h GException.h \
  DjVuGlobal.h GException.h DjVuMessageLite.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h DjVuGlobal.h
GURL.lo GURL.o: GURL.cpp ../config.h GException.h DjVuGlobal.h GOS.h DjVuGlobal.h \
  GString.h DjVuGlobal.h GContainer.h GException.h GSmartPointer.h \
  DjVuGlobal.h GURL.h GString.h Arrays.h GException.h GSmartPointer.h \
  GThreads.h DjVuGlobal.h GException.h debug.h
GUnicode.lo GUnicode.o: GUnicode.cpp ../config.h GString.h DjVuGlobal.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h \
  /opt/local/include/iconv.h
IFFByteStream.lo IFFByteStream.o: IFFByteStream.cpp ../config.h IFFByteStream.h \
  DjVuGlobal.h GException.h DjVuGlobal.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h
IW44EncodeCodec.lo IW44EncodeCodec.o: IW44EncodeCodec.cpp ../config.h IW44Image.h \
  GSmartPointer.h DjVuGlobal.h ZPCodec.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h ZPCodec.h GBitmap.h GSmartPointer.h \
  GPixmap.h GSmartPointer.h IFFByteStream.h DjVuGlobal.h GException.h \
  GString.h DjVuGlobal.h GContainer.h ByteStream.h Arrays.h GException.h \
  GSmartPointer.h GRect.h DjVuGlobal.h MMX.h DjVuGlobal.h
IW44Image.lo IW44Image.o: IW44Image.cpp ../config.h IW44Image.h GSmartPointer.h \
  DjVuGlobal.h ZPCodec.h GContainer.h GException.h DjVuGlobal.h \
  GSmartPointer.h ZPCodec.h GBitmap.h GSmartPointer.h GPixmap.h \
  GSmartPointer.h IFFByteStream.h DjVuGlobal.h GException.h GString.h \
  DjVuGlobal.h GContainer.h ByteStream.h Arrays.h GException.h \
  GSmartPointer.h GRect.h DjVuGlobal.h MMX.h DjVuGlobal.h
JB2EncodeCodec.lo JB2EncodeCodec.o: JB2EncodeCodec.cpp ../config.h JB2Image.h GString.h \
  DjVuGlobal.h GContainer.h GException.h DjVuGlobal.h GSmartPointer.h \
  DjVuGlobal.h ZPCodec.h GContainer.h GBitmap.h GSmartPointer.h
JB2Image.lo JB2Image.o: JB2Image.cpp ../config.h JB2Image.h GString.h DjVuGlobal.h \
  GContainer.h GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h \
  ZPCodec.h GContainer.h GThreads.h DjVuGlobal.h GException.h GRect.h \
  DjVuGlobal.h GBitmap.h GSmartPointer.h
JPEGDecoder.lo JPEGDecoder.o: JPEGDecoder.cpp ../config.h JPEGDecoder.h GSmartPointer.h \
  DjVuGlobal.h /opt/local/include/jconfig.h /opt/local/include/jpeglib.h \
  /opt/local/include/jconfig.h /opt/local/include/jmorecfg.h \
  /opt/local/include/jerror.h ByteStream.h Arrays.h GException.h \
  DjVuGlobal.h GSmartPointer.h GPixmap.h GSmartPointer.h
MMRDecoder.lo MMRDecoder.o: MMRDecoder.cpp ../config.h MMRDecoder.h GSmartPointer.h \
  DjVuGlobal.h JB2Image.h GString.h DjVuGlobal.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h ZPCodec.h GContainer.h \
  ByteStream.h Arrays.h GException.h GSmartPointer.h GBitmap.h \
  GSmartPointer.h
MMX.lo MMX.o: MMX.cpp ../config.h MMX.h DjVuGlobal.h
UnicodeByteStream.lo UnicodeByteStream.o: UnicodeByteStream.cpp ../config.h \
  UnicodeByteStream.h DjVuGlobal.h GString.h DjVuGlobal.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h ByteStream.h
XMLParser.lo XMLParser.o: XMLParser.cpp ../config.h XMLParser.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h DjVuGlobal.h GURL.h GString.h \
  DjVuGlobal.h GContainer.h Arrays.h GException.h GSmartPointer.h \
  GThreads.h DjVuGlobal.h GException.h XMLTags.h GContainer.h GString.h \
  ByteStream.h Arrays.h GOS.h DjVuGlobal.h GString.h DjVuDocument.h \
  DjVuPort.h GThreads.h GURL.h DjVuText.h GMapAreas.h GSmartPointer.h \
  GContainer.h GString.h GRect.h DjVuGlobal.h GURL.h DjVuAnno.h GString.h \
  DjVuFile.h DjVuInfo.h GSmartPointer.h GRect.h DjVuPalette.h \
  GContainer.h GPixmap.h GSmartPointer.h DjVuPort.h DjVuImage.h \
  DjVuFile.h DjVuAnno.h GRect.h debug.h
XMLTags.lo XMLTags.o: XMLTags.cpp ../config.h XMLTags.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h DjVuGlobal.h GString.h DjVuGlobal.h \
  GContainer.h UnicodeByteStream.h DjVuGlobal.h GString.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h
ZPCodec.lo ZPCodec.o: ZPCodec.cpp ../config.h ZPCodec.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h DjVuGlobal.h ByteStream.h Arrays.h \
  GException.h GSmartPointer.h GException.h
atomic.lo atomic.o: atomic.cpp ../config.h atomic.h GThreads.h DjVuGlobal.h \
  GException.h DjVuGlobal.h
ddjvuapi.lo ddjvuapi.o: ddjvuapi.cpp ../config.h GException.h DjVuGlobal.h \
  GSmartPointer.h DjVuGlobal.h GThreads.h DjVuGlobal.h GException.h \
  GContainer.h GException.h GSmartPointer.h ByteStream.h Arrays.h \
  GException.h GSmartPointer.h IFFByteStream.h DjVuGlobal.h GException.h \
  GString.h DjVuGlobal.h GContainer.h ByteStream.h BSByteStream.h \
  ByteStream.h GException.h ZPCodec.h GContainer.h GString.h GBitmap.h \
  GSmartPointer.h GPixmap.h GSmartPointer.h GScaler.h GException.h \
  GRect.h DjVuGlobal.h GBitmap.h GPixmap.h DjVuPort.h GThreads.h GURL.h \
  GString.h Arrays.h GThreads.h DataPool.h GThreads.h GString.h GURL.h \
  DjVuInfo.h GSmartPointer.h GRect.h IW44Image.h GSmartPointer.h \
  ZPCodec.h DjVuImage.h DjVuFile.h DjVuInfo.h DjVuPalette.h GContainer.h \
  GPixmap.h DjVuPort.h DjVuAnno.h GString.h GRect.h DjVuFileCache.h \
  DjVuFile.h DjVuDocument.h DjVuPort.h DjVuDumpHelper.h GSmartPointer.h \
  DjVuMessageLite.h GString.h DjVuMessage.h DjVuMessageLite.h DjVmNav.h \
  DjVuGlobal.h GString.h GThreads.h DjVuText.h GMapAreas.h \
  GSmartPointer.h GContainer.h GString.h GRect.h GURL.h DjVuAnno.h \
  DjVuToPS.h DjVuGlobal.h GRect.h DjVuDocument.h DjVuText.h DjVmDir.h \
  GString.h GThreads.h DjVmDir0.h GString.h DjVuNavDir.h GString.h \
  GThreads.h GURL.h DjVmDoc.h DjVmDir.h miniexp.h ddjvuapi.h
debug.lo debug.o: debug.cpp ../config.h debug.h
miniexp.lo miniexp.o: miniexp.cpp ../config.h miniexp.h
