.\" Copyright (c) 2001 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\"                    AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.

.TH DJVU 1 "10/11/2001" "DjVu" "DjVu open software"
.SH NAME
djvu \- Overview of the djvu open software
.SH INTRODUCTION
Introduction to djvu.
.SS DjVuPhoto
blabla
.SS DjVuBitonal
blabla
.SS DjVuDocument
blabla

.SH MULTIPAGE DOCUMENTS
blabla
.SS Bundled multipage documents
blabla
.SS Indirect multipage documents
blabla

.SH ANCILLARY INFORMATION
blabla
.SS Annotations
blabla
.SS Thumbnails
blabla
.SS Hidden Text
blabla

.SH DJVU OPEN SOFTWARE
Various command line tools are provided:
.PP
.B annotate
-- does something.
.PP
.B bzz
-- does something.
.PP
.B c44
-- does something.
.PP
.B cjb2
-- does something.
.PP
.B cpaldjvu
-- does something.
.PP
.B csepdjvu
-- does something.
.PP
.B ddjvu
-- does something.
.PP
.B djthumb
-- does something.
.PP
.B djview
-- does something.
.PP
.B djvm
-- does something.
.PP
.B djvmcvt
-- does something.
.PP
.B djvudump
-- does something.
.PP
.B djvuextract
-- does something.
.PP
.B djvumake
-- does something.
.PP
.B djvused
-- does something.
.PP
.B djvutxt
-- does something.

