bzz.o: bzz.cpp ../config.h ../libdjvu/GException.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/ByteStream.h ../libdjvu/Arrays.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/BSByteStream.h \
  ../libdjvu/ByteStream.h ../libdjvu/GException.h ../libdjvu/ZPCodec.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h \
  ../libdjvu/GURL.h ../libdjvu/GString.h ../libdjvu/Arrays.h \
  ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h ../libdjvu/GException.h \
  ../libdjvu/DjVuMessage.h ../libdjvu/DjVuMessageLite.h \
  ../libdjvu/GString.h
c44.o: c44.cpp ../config.h ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/IW44Image.h ../libdjvu/GSmartPointer.h ../libdjvu/ZPCodec.h \
  ../libdjvu/GContainer.h ../libdjvu/DjVuInfo.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GRect.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/IFFByteStream.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GString.h ../libdjvu/ByteStream.h \
  ../libdjvu/Arrays.h ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h \
  ../libdjvu/GBitmap.h ../libdjvu/GSmartPointer.h ../libdjvu/GPixmap.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GURL.h ../libdjvu/GString.h \
  ../libdjvu/Arrays.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuMessage.h \
  ../libdjvu/DjVuMessageLite.h ../libdjvu/GString.h \
  ../libdjvu/JPEGDecoder.h ../libdjvu/GSmartPointer.h
cjb2.o: cjb2.cpp ../config.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/ByteStream.h ../libdjvu/Arrays.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/IFFByteStream.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/ByteStream.h ../libdjvu/GRect.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GBitmap.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/JB2Image.h ../libdjvu/GString.h ../libdjvu/ZPCodec.h \
  ../libdjvu/GContainer.h ../libdjvu/DjVuInfo.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GRect.h ../libdjvu/GOS.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h ../libdjvu/GURL.h \
  ../libdjvu/GString.h ../libdjvu/Arrays.h ../libdjvu/GThreads.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GException.h \
  ../libdjvu/DjVuMessage.h ../libdjvu/DjVuMessageLite.h \
  ../libdjvu/GString.h jb2tune.h
cpaldjvu.o: cpaldjvu.cpp ../config.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/ByteStream.h ../libdjvu/Arrays.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/IFFByteStream.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/ByteStream.h ../libdjvu/GRect.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GBitmap.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/JB2Image.h ../libdjvu/GString.h ../libdjvu/ZPCodec.h \
  ../libdjvu/GContainer.h ../libdjvu/DjVuPalette.h \
  ../libdjvu/GContainer.h ../libdjvu/GPixmap.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/IW44Image.h ../libdjvu/GSmartPointer.h ../libdjvu/ZPCodec.h \
  ../libdjvu/DjVuInfo.h ../libdjvu/GSmartPointer.h ../libdjvu/GRect.h \
  ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h \
  ../libdjvu/GURL.h ../libdjvu/GString.h ../libdjvu/Arrays.h \
  ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h ../libdjvu/GException.h \
  ../libdjvu/DjVuMessage.h ../libdjvu/DjVuMessageLite.h \
  ../libdjvu/GString.h jb2tune.h
csepdjvu.o: csepdjvu.cpp ../config.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/ByteStream.h ../libdjvu/Arrays.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/IFFByteStream.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/ByteStream.h ../libdjvu/GRect.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GBitmap.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/JB2Image.h ../libdjvu/GString.h ../libdjvu/ZPCodec.h \
  ../libdjvu/GContainer.h ../libdjvu/DjVuPalette.h \
  ../libdjvu/GContainer.h ../libdjvu/GPixmap.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/IW44Image.h ../libdjvu/GSmartPointer.h ../libdjvu/ZPCodec.h \
  ../libdjvu/DjVuInfo.h ../libdjvu/GSmartPointer.h ../libdjvu/GRect.h \
  ../libdjvu/DjVmDoc.h ../libdjvu/DjVmDir.h ../libdjvu/GString.h \
  ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h ../libdjvu/GException.h \
  ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h \
  ../libdjvu/GURL.h ../libdjvu/GString.h ../libdjvu/Arrays.h \
  ../libdjvu/GThreads.h ../libdjvu/DjVuMessage.h \
  ../libdjvu/DjVuMessageLite.h ../libdjvu/GString.h ../libdjvu/DjVuText.h \
  ../libdjvu/GMapAreas.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GContainer.h ../libdjvu/GString.h ../libdjvu/GRect.h \
  ../libdjvu/GURL.h ../libdjvu/BSByteStream.h ../libdjvu/ByteStream.h \
  ../libdjvu/GException.h ../libdjvu/ZPCodec.h jb2tune.h
ddjvu.o: ddjvu.cpp ../config.h ../libdjvu/ddjvuapi.h
djvm.o: djvm.cpp ../config.h ../libdjvu/GException.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/DjVuDocEditor.h \
  ../libdjvu/DjVuDocument.h ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GException.h ../libdjvu/GURL.h \
  ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/Arrays.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GThreads.h ../libdjvu/DjVmDoc.h \
  ../libdjvu/DjVmDir.h ../libdjvu/GString.h ../libdjvu/GThreads.h \
  ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h \
  ../libdjvu/DjVuMessage.h ../libdjvu/DjVuMessageLite.h \
  ../libdjvu/GString.h
djvmcvt.o: djvmcvt.cpp ../config.h ../libdjvu/DjVuDocument.h \
  ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h ../libdjvu/GURL.h \
  ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/Arrays.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GThreads.h ../libdjvu/DjVmDoc.h \
  ../libdjvu/DjVmDir.h ../libdjvu/GString.h ../libdjvu/GThreads.h \
  ../libdjvu/ByteStream.h ../libdjvu/Arrays.h ../libdjvu/GOS.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h ../libdjvu/DjVuMessage.h \
  ../libdjvu/DjVuMessageLite.h ../libdjvu/GString.h ../libdjvu/debug.h
djvudump.o: djvudump.cpp ../config.h ../libdjvu/DjVuDumpHelper.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/ByteStream.h ../libdjvu/Arrays.h ../libdjvu/GException.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GSmartPointer.h ../libdjvu/GOS.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GURL.h ../libdjvu/GString.h \
  ../libdjvu/Arrays.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuMessage.h \
  ../libdjvu/DjVuMessageLite.h ../libdjvu/GString.h
djvuextract.o: djvuextract.cpp ../config.h ../libdjvu/GException.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/ByteStream.h ../libdjvu/Arrays.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/IFFByteStream.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GException.h ../libdjvu/GString.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/ByteStream.h \
  ../libdjvu/DjVuDocument.h ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GException.h ../libdjvu/GURL.h \
  ../libdjvu/GString.h ../libdjvu/Arrays.h ../libdjvu/GThreads.h \
  ../libdjvu/DjVuFile.h ../libdjvu/DjVuInfo.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GRect.h ../libdjvu/DjVuGlobal.h ../libdjvu/DjVuPalette.h \
  ../libdjvu/GContainer.h ../libdjvu/GPixmap.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuPort.h ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GString.h ../libdjvu/DjVuMessage.h \
  ../libdjvu/DjVuMessageLite.h ../libdjvu/GString.h
djvumake.o: djvumake.cpp ../config.h ../libdjvu/GString.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/DjVuImage.h ../libdjvu/DjVuFile.h \
  ../libdjvu/DjVuInfo.h ../libdjvu/GSmartPointer.h ../libdjvu/GRect.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/DjVuPalette.h \
  ../libdjvu/GContainer.h ../libdjvu/GPixmap.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GURL.h ../libdjvu/GString.h \
  ../libdjvu/Arrays.h ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GThreads.h ../libdjvu/DjVuAnno.h ../libdjvu/GString.h \
  ../libdjvu/GRect.h ../libdjvu/MMRDecoder.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/IFFByteStream.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GString.h ../libdjvu/ByteStream.h \
  ../libdjvu/Arrays.h ../libdjvu/JB2Image.h ../libdjvu/GString.h \
  ../libdjvu/ZPCodec.h ../libdjvu/GContainer.h ../libdjvu/IW44Image.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/ZPCodec.h ../libdjvu/GBitmap.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuMessage.h \
  ../libdjvu/DjVuMessageLite.h ../libdjvu/GString.h
djvups.o: djvups.cpp ../config.h ../libdjvu/ddjvuapi.h
djvused.o: djvused.cpp ../config.h ../libdjvu/IW44Image.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuGlobal.h ../libdjvu/ZPCodec.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h \
  ../libdjvu/DjVuDocEditor.h ../libdjvu/DjVuDocument.h \
  ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GURL.h ../libdjvu/GString.h \
  ../libdjvu/Arrays.h ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GThreads.h ../libdjvu/DjVmDoc.h ../libdjvu/DjVmDir.h \
  ../libdjvu/GString.h ../libdjvu/GThreads.h ../libdjvu/DjVuDumpHelper.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/BSByteStream.h \
  ../libdjvu/ByteStream.h ../libdjvu/Arrays.h ../libdjvu/GException.h \
  ../libdjvu/ZPCodec.h ../libdjvu/DjVuText.h ../libdjvu/GMapAreas.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GContainer.h ../libdjvu/GString.h \
  ../libdjvu/GRect.h ../libdjvu/DjVuGlobal.h ../libdjvu/GURL.h \
  ../libdjvu/DjVuAnno.h ../libdjvu/GString.h ../libdjvu/DjVuInfo.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GRect.h \
  ../libdjvu/IFFByteStream.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GString.h ../libdjvu/ByteStream.h \
  ../libdjvu/DataPool.h ../libdjvu/GThreads.h ../libdjvu/GString.h \
  ../libdjvu/GURL.h ../libdjvu/DjVuFile.h ../libdjvu/DjVuInfo.h \
  ../libdjvu/DjVuPalette.h ../libdjvu/GContainer.h ../libdjvu/GPixmap.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuPort.h ../libdjvu/DjVmNav.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h ../libdjvu/GThreads.h
djvuserve.o: djvuserve.cpp ../config.h ../libdjvu/DjVuDocument.h \
  ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h ../libdjvu/GURL.h \
  ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/Arrays.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GThreads.h ../libdjvu/DjVmDir.h \
  ../libdjvu/GString.h ../libdjvu/GThreads.h ../libdjvu/ByteStream.h \
  ../libdjvu/Arrays.h ../libdjvu/IFFByteStream.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/GString.h ../libdjvu/ByteStream.h \
  ../libdjvu/DjVuText.h ../libdjvu/GMapAreas.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GContainer.h ../libdjvu/GString.h ../libdjvu/GRect.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GURL.h ../libdjvu/DjVuImage.h \
  ../libdjvu/DjVuFile.h ../libdjvu/DjVuInfo.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GRect.h ../libdjvu/DjVuPalette.h ../libdjvu/GContainer.h \
  ../libdjvu/GPixmap.h ../libdjvu/GSmartPointer.h ../libdjvu/DjVuPort.h \
  ../libdjvu/DjVuAnno.h ../libdjvu/GString.h ../libdjvu/GRect.h \
  ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h \
  ../libdjvu/DjVuMessage.h ../libdjvu/DjVuMessageLite.h \
  ../libdjvu/GString.h
djvutxt.o: djvutxt.cpp ../config.h ../libdjvu/DjVuDocument.h \
  ../libdjvu/DjVuPort.h ../libdjvu/GThreads.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h ../libdjvu/GURL.h \
  ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h \
  ../libdjvu/GException.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/Arrays.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GThreads.h \
  ../libdjvu/ByteStream.h ../libdjvu/Arrays.h ../libdjvu/DjVuText.h \
  ../libdjvu/GMapAreas.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GContainer.h ../libdjvu/GString.h ../libdjvu/GRect.h \
  ../libdjvu/DjVuGlobal.h ../libdjvu/GURL.h ../libdjvu/DjVuImage.h \
  ../libdjvu/DjVuFile.h ../libdjvu/DjVuInfo.h ../libdjvu/GSmartPointer.h \
  ../libdjvu/GRect.h ../libdjvu/DjVuPalette.h ../libdjvu/GContainer.h \
  ../libdjvu/GPixmap.h ../libdjvu/GSmartPointer.h ../libdjvu/DjVuPort.h \
  ../libdjvu/DjVuAnno.h ../libdjvu/GString.h ../libdjvu/GRect.h \
  ../libdjvu/GOS.h ../libdjvu/DjVuGlobal.h ../libdjvu/GString.h \
  ../libdjvu/DjVuMessage.h ../libdjvu/DjVuMessageLite.h \
  ../libdjvu/GString.h
jb2tune.o: jb2tune.cpp ../config.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GException.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GContainer.h ../libdjvu/GException.h \
  ../libdjvu/GSmartPointer.h ../libdjvu/GRect.h ../libdjvu/DjVuGlobal.h \
  ../libdjvu/GBitmap.h ../libdjvu/GSmartPointer.h ../libdjvu/JB2Image.h \
  ../libdjvu/GString.h ../libdjvu/DjVuGlobal.h ../libdjvu/GContainer.h \
  ../libdjvu/ZPCodec.h ../libdjvu/GContainer.h jb2tune.h \
  jb2cmp/minidjvu.h jb2cmp/patterns.h jb2cmp/classify.h jb2cmp/patterns.h \
  jb2cmp/classify.h
