.\" -*- coding: euc-jp -*-
.\" Copyright (c) 2001 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\"                    AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVIEW 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.SH "名前"
djview \- スタンドアロン DjVu ビューア

.SH 書式
.BI "djview [" "オプション" "] [" "DjVu ファイル" "]"

.SH 説明
DjVu ファイルのスタンドアロンビューアです。
主な機能は；
文書のページ移動、
ページのズームやパン、
サムネイルの生成と表示、
テキストレイヤの単語検索、
テキストのコピー、
ページを
.SM PNM
形式でエクスポート、
バンドルドまたはインダイレクト形式のマルチページ形式で
ページまたは文書を保存、
ポストスクリプトプリンタへの印刷。

.SH オプション
.TP
.B "-help"
簡易のヘルプメッセージを表示します。
.TP
.BI "-page " "pagenum"
.I pagenum
に指定したページを開きます
.TP
.BI "-style=" "stylename"
GUI のスタイルを指定します。
.I stylename
へ設定できる値はインストールされている
Qt ツールキットのバージョンによって異なります。
共通スタイル名には、
.BR windows、
.BR motif、
.BR motifplus、
.BR sgi、
.BR cde、
.BR platinum
のいずれかを指定します。
.TP
.BI "-fullscreen, -fs "
djview を全画面モードで起動します。
この機能は DjVu ファイル名をコマンドラインに指定した
場合にのみ動作します。
.TP
.BI "-geometry " "geom"
初期ウィンドウサイズを指定します。
.SM X11
のジオメトリ仕様
.I geom
は通常
.BI "" w x h + x + y
の形式を採用します。
.IR w " および " h
はウィンドウの幅と高さを表し、
.IR x " および " y
ウィンドウの位置を表します。
.TP
.BI "-display " "disp"
.B djview
のウィンドウを
.SM X11
ディスプレイ
.IR disp .
に表示します。
.TP
.BI "-fn " "fontname"
ボタンやメニューで使用されるデフォルトフォントの
名前を指定します。
.TP
.BI "-bg " "color"
デフォルトの背景色を指定します。
.TP
.BI "-fg " "color"
デフォルトの前景色を指定します。
.TP
.BI "-btn " "color"
デフォルトボタンの色を指定します。
.TP
.B "-visual TrueColor"
8 ビットディスプレイで強制的に TrueColor を使用します。
.TP
.B "-ncols " "count"
8 ビットディスプレイでカラーパレットの色数を限定します。
デフォルトは 216 色です。
.TP
.B "-cmap"
8 ビットディスプレイで
.B djview
にユーザ定義のカラーマップをインストールさせます。
.TP
.B "-fix"
ファイル
.B $HOME/.mailcap 
および
.B $HOME/.mime.types
をチェックして、
認識可能な DjVu エントリの再構築を試みます。
この機能は DjVu プラグインが動作する場合に役立ちます。

.SH 使い方

多くの機能はメニューやツールバー、ポップアップメニューからアクセスすることが可能です。
ポップアップメニューは、DjVu 画像の上でマウスの右ボタンを押したままにすると表示されます。
ツールバーは通常は DjVu 画像の下部に表示されます。初期設定ダイアログで、ツールバーを
無効にしたり「自動的に隠す」モードを設定することが出来ます。

以下のキーボードショートカットが利用できます:
.PP
.TS
center,box;
lfB lfB
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
.
キー	動作
=
1, 2, 3	それぞれズームレベルを 100%、200%、300% に設定します。
Up, Down, Left, Right	押されたキーの方向へスクロールします。
Home	画像の左上隅を表示します。
End	画像の右下隅を表示します。
Control+Home	マルチページ文書の先頭へ移動します。
Control+End	マルチページ文書の最後へ移動します。
Space, Return	画面の下方へスクロールするか、次のページへ移動します。
Backspace	画面の上方へスクロールするか、前のページへ移動します。
Page Down	次のページへ移動します。
Page Up	前のページへ移動します。
+, -	ズームインまたはズームアウト
W	「幅にあわせる」ズームモードを設定します。
P	「ページにあわせる」ズームモードを設定します。
G	「ページ移動」ダイアログを表示します。
F, F3, CTRL+F	テキストレイヤを検索します。
CTRL	拡大鏡を表示します。
.TE
.PP

.SH クレジット
このプログラムは Andrei Erofeev <andrew_erofeev@yahoo.com>
が開発し、
Bill Riemers <docbill@sourceforge.net> および
L\('eon Bottou <leonb@users.sourceforge.net>
が改良しました。
このプログラムおよび man page は Nobchika Morimoto <morimoto@lizardtech.com>
が翻訳しました。

.SH 参照
.BR djvu (1)、
.BR ddjvu (1)、
.BR nsdejavu (1)
