.\" -*- coding: euc-jp -*-
.\" Copyright (c) 2001-2003 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\" Copyright (c) 2001 AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVMCVT 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.de SS
.SH \\0\\0\\0\\$*
..
.SH 名前
djvmcvt \- マルチページ DjVu 文書を変換します。

.SH 書式
.SS バンドルド形式を作成します:
.BI "djvmcvt -b[undled] " "docin.djvu" " " "docout.djvu"
.SS インダイレクト形式を作成します:
.BI "djvmcvt -i[ndirect] " "docin.djvu" " " "dir" " " "index.djvu"

.SH 説明
このプログラムはあらゆるマルチページ形式の DjVu 文書を
バンドルド形式またはインダイレクト形式のマルチページ形式へ
変換します。
入力ファイル
.I docin.djvu
はバンドル形式の文書、またはインダイレクト形式の
インデックスファイルである必要があります。

.SH オプション
.TP
.B -b[undled]
.IR docout.djvu
に指定されたバンドルド形式のマルチページ DjVu 文書を作成します。
.TP
.B -i[ndirect]
インダイレクト形式のマルチページ DjVu 文書を作成します。
インダイレクト形式を構成する全てのファイルはディレクトリ
.IR dir
に保存されます。
インデックスファイルは
.IR index.djvu
に指定された名前で保存されます。

.SH クレジット
このプログラムは Andrei Erofeev <andrew_erofeev@yahoo.com>
が開発し、
Bill Riemers <docbill@sourceforge.net>
その他の方々により改良されました。
この man page は Nobchika Morimoto <morimoto@lizardtech.com>
が翻訳しました。

.SH 参照
.BR djvu (1)、
.BR djvmcvt (1)

