.\" -*- coding: euc-jp -*-
.\" Copyright (c) 2001-2003 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\" Copyright (c) 2001 AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVUSED 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.de SS
.SH \\0\\0\\0\\$*
..
.SH 名前
djvused \- 多目的 DjVu 文書エディタ。

.SH SYNOPSIS
.BI "djvused [" "options" "] " "djvufile"

.SH 説明
プログラム
.B djvused
はマルチページ文書を作成したり、アノテーションチャンクやテキストレイヤの編集、
サムネイルの作成などを行うための強力なコマンドラインツールです。プログラムは
.I djvufile
に指定された DjVu 文書を読み込み、djvused の様々なコマンドを実行します。

djvused のコマンドは特定のファイルから読み込んだり(オプション
.B -f
が指定されている場合)、コマンドラインから読み込んだり(オプション
.B -e
が指定されている場合)、標準入力から読み込む(デフォルト)ことが可能です。

.SH オプション
.TP
.BI "-v"
.B djvused
はコマンドを読み込む前にコマンドラインプロンプトを出力し、
コマンドの処理状況を示すメッセージを出力します。このオプションは
djvused のスクリプトをデバッグしたり、
djvused のコマンドを標準入力から入力したりするのに非常に便利です。
.TP
.BI "-f " "scriptfile"
.B djvused
はファイル
.IR scriptfile
からコマンドを読み込みます。
.TP
.BI "-e " "command"
.B djvused
はオプション引数
.IR commands
に指定されたコマンドを実行します。
シェルが不必要にコマンドを展開するのを防ぐために
コマンドをシングルクォーテーションで
囲むことをお勧めします。
.TP
.BI "-s"
.B djvused
は指定されたコマンドを実行した後、ファイル
.I djvufile
に保存します。
これはプログラムの終了直前に
.B save
コマンドを実行するのと同じです。
.TP
.BI "-n"
.B djvused
は save コマンドを無視します。
これはローカルディスクのファイルを上書きせずに
 djvused スクリプトをデバッグするのに便利です。

.SH 使用方法
.BR djvused
の使い方はたくさんあります。
以下の例ではいくつかの代表的な使用方法
をご紹介します。

.SS ページサイズの取得
コマンド
.B size
は
.SM HTML
のような書式で選択したページの幅と高さを返します。
たとえば、以下のコマンドは
.IR myfile.djvu
の
.I 3
.IP "" 3
.BI "djvused " "myfile.djvu" " -e 'select 3; size'"
.PP

.SS テキストの書き出し
コマンド
.B print-pure-txt
はページまたは文書に関連付けられたテキストを出力します。
たとえば、以下のコマンドは文書全体のテキストを出力します。
行やページは通常のコントロール文字で区切られます。
.IP "" 3
.BI "djvused " "myfile.djvu" " -e 'print-pure-txt'"
.PP
コマンド
.B print-txt
はテキストコンポーネントの構造や位置を示す情報を持った拡張テキストを
出力します。書式はこの man page の後半で解説します。たとえば、以下
のコマンドは
.IR myfile.djvu
の
.I 3
ページ目の拡張テキスト情報を出力します。
.IP "" 3
.BI "djvused " "myfile.djvu" " -e 'select 3; print-txt'"
.PP

.SS アノテーションの書き出し
アノテーションデータはコマンド
.BR print-ant
で書き出すことが出来ます。
アノテーションデータの書式はこの man page の後半で解説します。たとえば、
以下のコマンドは
.BR myfile.djvu
の最初のページのアノテーションデータを出力します。
.IP "" 3
.BI "djvused " "myfile.djvu" " -e 'select 1; print-ant'"
.PP
コマンド
.B print-ant
は選択されたコンポーネントファイルに含まれるアノテーションだけを
出力します。
コマンド
.B print-merged-ant
は現在のページが(
.SM INCL
を使用して)参照している全てのコンポーネントファイルから
アノテーションを取得し、マージした情報を返します。

.SS アノテーションやテキストのダンプとリストア
3 つのコマンド
.BR "output-txt" "、" "output-ant" "、" "output-all"
は djvused スクリプトを生成します。たとえば、以下のコマンドは
djvused スクリプト
.IR myfile.dsed
を生成します。このスクリプトは
.IR myfile.djvu
に含まれる全てのテキストとアノテーションデータを再作成します。
.IP "" 3
.BI "djvused " "myfile.djvu" " -e 'output-all' > " "myfile.dsed"
.PP
スクリプト
.I myfile.dsed
は簡単に編集することが出来るテキストファイルです。以下のコマンドは
ファイル
.IR myfile.djvu
のテキストとアノテーション情報を再作成します。
.IP "" 3
.BI "djvused " "myfile.djvu" " -f " "myfile.dsed" " -s"

.SS ページの書き出し
2 つのコマンド
.B save-page
と
.B save-page-with
は分書中の選択されたコンポーネントファイルを示す DjVu ファイルを作成します。
たとえば、以下のコマンドは文書
.IR myfile.djvu
の
.I 5
ページ目を含むファイル
.I p05.djvu
.IP "" 3
.BI "djvused " "myfile.djvu" " -e 'select 5; save-page " "p05.djvu" "'"
.PP
文書の各ページは、いわゆる inclusion チャンク(
.SM INCL
)を使用して別のコンポーネントファイルからのデータを
インポートすることがあります。
そして、コマンド
.B save-page
はインポートされたデータへの未解決の参照を含んだファイルを作成します。
このようなファイルは、別のコンポーネントファイルが必要とするデータ
をもつマルチページ文書の一部として作成されます。
これに対して、コマンド
.B save-page-with
は全てのインポートされたデータを出力ファイルにコピーします。
このファイルは直接使うことが出来ます。しかし、そのようなファイルを 1
つのマルチページ文書に集めると不必要にデータを複製してしまう可能性があります。

.SS サムネイルの作成
コマンド
.B set-thumbnails
は DjVu ビューアが表示に使用するサムネイルを作成します。
たとえば、以下の例は、ファイル
.IR myfile.djvu
の全てのページにサイズ
.IR 64 x 64
ピクセルでサムネイルを作成します。
.IP "" 3
.BI "djvused " "myfile.djvu" " -e 'set-thumbnails 64'"

.SH コマンド
コマンドラインには一つまたは複数の djvused コマンドやオプションコメント
が含まれていたり、全く含まれていないこともあります。複数の djvused コマンド
はセミコロン「;」で区切ります。コメントは「#」に続けて記述し、行末まで
コメントとして認識されます。

.SS 選択コマンド
マルチページの DjVu 文書は複数のコンポーネントファイルで構成されます。
ほとんどのコンポーネントファイルは、文書の特定のページに相当します。
コンポーネントの中には共有画像データや共有アノテーション、サムネイルのように
複数のページで共有されるものもあります。多くの djvused コマンドは
選択したコンポーネントファイルに有効です。全てのコンポーネントファイルは
最初は選択されています。以下のコマンドは選択状態を変更するのに使用します。
.TP
.BI "ls"
文書中の全てのコンポーネントファイルを選択します。各行は
オプションのページ番号や、コンポーネントファイルのタイプを示す文字、
コンポーネントファイルのサイズ、コンポーネントファイルの識別子を含みます。
コンポーネントファイルのタイプを示す文字
.BR P "、" I "、" A "、" T
はそれぞれページデータ、共有画像データ、共有アノテーションデータ、サムネイルデータ
を示します。ページ番号はページデータを含むコンポーネントファイルにのみ
リストされています。
.TP
.BI "select [" "fileid" "]"
引数
.IR fileid
で認識されたコンポーネントを選択します。
引数
.I fileid
はページ番号またはコンポーネントファイルの識別子を指定します。
.B select
コマンドは引数
.I fileid
が省略された場合、
全てのコンポーネントファイルを選択します。
.TP
.BI "select-shared-ant"
共有アノテーションを含むコンポーネントファイルを選択します。
現バージョンの DjVu ソフトウェアではこのようなファイルは一つだけ
サポートされています。このコンポーネントファイルは通常特定のページ
ではなく文書全体に属するアノテーションを保持します。このコンポーネント
ファイルが存在しないとエラーが発生します。
.TP
.BI "create-shared-ant"
共有アノテーションを含むコンポーネントファイルを作成して選択します。
このコマンドは共有アノテーションコンポーネントが既に存在する場合は
共有アノテーションコンポーネントのみを選択します。存在しない場合は、
新しい共有アノテーションコンポーネントを作成し、文書中の全てのページ
からインポートされていることを確認します。

.SS 様々なコマンド
.TP
.BI "help"
.BR djvused
がサポートする全てのコマンドのヘルプメッセージを表示します。
.TP
.BI "n"
文書中の総ページ数を表示します。
.TP
.BI "dump"
文書または選択されたコンポーネントファイルの
.SM EA IFF 85
構造を表示します。
同様の機能はプログラム
.BR djvudump
でも提供されています。
.TP
.BI "size"
選択されたページの幅と高さを表示します。各ページのサイズは
.SM <EMBED...></EMBED>
タグで直接挿入するのに適した書式で表示されます。

.SS テキストおよびアノテーションコマンド
.TP
.BI "print-pure-txt"
選択したページのテキストレイヤのテキストを出力する。同様の機能は
プログラム
.BR djvutxt
も提供しています。
構造化情報はコントロール文字で表されることがあります。ページ毎のテキストは
フィード文字「\\f」で区切られます。行は改行コード「\\n」で区切られます。
カラムや、領域、パラグラフはそれぞれ、タブ文字「\\013」、グループセパレータ「\\035」、
ユニットセパレータ「\\037」で区切られます。
.TP
.BI "print-txt"
選択されたページのテキスト情報を出力します。
この情報は文書中のページのテキスト構造を表し、ページ画像中の構造化要素
の位置を特定します。
出力の書式は、この man page の後半で解説します。
.TP
.BI "remove-txt"
選択されたコンポーネントファイルからテキスト情報を削除します。
たとえば、コマンド
.BR "select" "および" "remove-txt"
を実行すると、DjVu 文書中の全てのテキスト情報が削除されます。
.TP
.BI "set-txt [" "djvusedtxtfile" "]"
選択したページにテキスト情報を挿入します。
オプション引数
.I djvusedtxtfile
はテキスト情報を含むファイルの名前です。
このファイルはコマンド
.BR print-txt
で作成される内容と同じでなければなりません。
オプション引数が省略された場合、
プログラムはピリオドか EOF が見つかるまで djvused スクリプトから
テキスト情報を読み続けます。
.TP
.BI "output-txt"
選択したページのテキスト情報を再構築する djvused スクリプトを
出力します。このスクリプトは
.B djvused
プログラムを
.BR -f
オプション付で起動することで、後で編集したり実行することが出来ます。
.TP
.BI "print-ant"
選択されたコンポーネントファイルのアノテーションを出力します。
アノテーションデータは後述するシンプルな書式で出力されます。
.TP
.BI "print-merged-ant"
選択されたコンポーネントファイルに保存されたアノテーションを
共有アノテーションファイルなどからインポートしたアノテーションへ
マージします。
アノテーションデータは後述するシンプルな書式で出力されます。
.TP
.BI "remove-ant"
選択されたコンポーネントファイルからアノテーション情報を削除します。
たとえば、コマンド
.BR "select" "および" "remove-ant"
を実行すると DjVu 文書から全てのアノテーション情報を削除します。
.TP
.BI "set-ant [" "djvusedantfile" "]"
選択したコンポーネントファイルのアノテーションを設定します。
オプション引数の
.I djvusedantfile
はアノテーションデータを含むファイルの名前です。
このファイルはコマンド
.BR print-ant
が出力する内容と同じでなくてはなりません。
オプション引数が省略された場合、
プログラムはピリオドか EOF が見つかるまで djvused スクリプトから
テキスト情報を読み続けます。
.TP
.BI "output-ant"
選択したページのアノテーション情報を再構築する
djvused スクリプトを出力します。このスクリプトは
.B djvused
プログラムを
.BR -f
オプション付で起動することで、後で編集したり実行することが出来ます。
.TP
.BI "print-meta"
選択したコンポーネントファイルののアノテーションからメタデータの部分を出力します。
このコマンドは
.B print-ant
コマンドが出力する情報のサブセットを異なる書式で表示します。メタデータは
キーと値のペアで構成されています。各行は
.BR "author" "、" "title"
などのキー名を含み、その後にタブ文字「\\t」とダブルクォーテーションで囲まれた
.SM UTF-8
エンコードのメタデータ文字列が続きます。
.TP
.BI "set-meta " "djvusedmetafile"
選択したコンポーネントファイルのアノテーションからメタデータの部分を設定します。
アノテーションの他の部分は変更されません。
オプション引数
.I djvusedmetafile
はメタデータを含むファイルの名前です。
このファイルはコマンド
.BR print-meta
が出力する内容と同じでなくてはなりません。
オプション引数が省略された場合、
プログラムはピリオドか EOF が見つかるまで djvused スクリプトから
テキスト情報を読み続けます。
.TP
.BI "output-all"
選択したページのテキストおよびアノテーション情報を再構築する
djvused スクリプトを出力します。このスクリプトは
.B djvused
プログラムを
.BR -f
オプション付で起動することで、後で編集したり実行することが出来ます。

.SS サムネイルコマンド
.TP
.BI "set-thumbnails " "sz"
サムネイルサイズ
.IR sz x sz
ピクセルを計算し文書に挿入します。
DjVu ビューアは各ページのデータをダウンロードしなくても
非常に効果的にサムネイルを表示することが出来ます。
通常サムネイルサイズは 48 から 128 の間で指定します。
.TP
.BI "remove-thumbnails"
DjVu 文書からサムネイルを削除します。
コマンド
.BR set-thumbnails
で新しいサムネイルを作成することが出来ます。

.SS Save commands
上記のコマンドはメモリ上の DjVu 文書を変更するだけです。
以下のコマンドは変更したデータをファイルシステムに保存する方法を
提供します。
.TP
.BI "save"
プログラム
.BR djvused
の引数に指定された入力ファイル
.I djvufile
に変更された DjVu 文書を保存しなおします。
DjVu ファイルが変更されなかった場合は何もしません。
オプション
.B -s
を指定するのはプログラム終了前にコマンド
.B save
を実行するのと同じです。
.TP
.BI "save-bundled " "filename"
現在の DjVu 文書をバンドルド形式の DjVu 文書
として
.IR filename
に指定された名前で保存します。
同様の機能はプログラム
.BR djvmcvt
でも提供されています。
.TP
.BI "save-indirect " "filename"
現在の DjVu 文書をインダイレクト形式のマルチページ文書として
保存します。インダイレクト形式のインデックスファイル名は
.BR filename
です。
同様の機能は
.BR djvmcvt
でも提供されています。
.TP
.BI "save-page " "filename"
選択されたコンポーネントファイルを
.IR filename
という DjVu ファイルに保存します。
選択されたコンポーネントファイルはいわゆる inclusion
チャンク(
.SM INCL
)を使用して他のコンポーネントファイルからインポート
されたデータである可能性があります。このコマンドは
インポートされたデータへの未解決の参照を含むファイルを作成します。
このようなファイルは、他のコンポーネントファイルに必要なデータを含む
マルチページ文書の一部にしておく必要があります。
.TP
.BI "save-page-with " "filename"
選択されたコンポーネントファイルを
.IR filename
という DjVu ファイルに保存します。
別のコンポーネントファイルからインポートされた全てのデータは出力ファイル
にも同様にコピーされます。このコマンドは常に使用可能な DjVu ファイルを作成します。
一方、このようなページをマルチページ文書内に複数集めることと、不必要にデータを
重複させてしまう可能性があります。


.SH djvused ファイル形式

djvused はアノテーションやテキストをあらわすのにシンプルな
括弧付の書式を使用します。
.IP "*" 3
この書式は DjVu がアノテーションを保存するのに使用される標準の書式です。
プログラム
.B djvused
は単に
.BR bzz (1)
アルゴリズムを使用してアノテーションデータを圧縮するだけです。
.IP "*" 3
この書式は DjVu がテキストを保存するのに使用する書式とは異なります。
プログラム
.B djvused
は DjVu が使用するコンパクトなバイナリ形式と編集が容易な括弧付の形式の
間で変換を行います。
.PP

.SS 一般的な書式
djvused ファイルは
.SM ASCII
テキストファイルです。djvused ファイルで有効な文字は
印字可能な
.SM ASCII 
文字とスペース、タブ、cr、nl 文字です。
これ以外の文字を使用した場合の結果は見て意義です。

djvused ファイルは空白文字(文字、スペース、タブ、cr、nl)で区切られた
一続きの式で構成されます。
式には整数、シンボル、文字列、リストの 4 種類があります。
.IP 整数:
製数値は通常通り複数の桁で表現されます。
.IP シンボル:
シンボルつまり識別子は名前やキーワードを示す一続きの印刷可能な文字です。使用できる
文字はアルファベットおよび数字、アンダースコア「_」、マイナス「-」、シャープ「#」
(全て半角)です。名前は、数字やマイナス記号ではじめてはいけません。
.IP 文字列:
文字列は任意のバイトシーケンス、通常は
S.SM UTF-8
エンコードの文字として認識されるシーケンスを表示します。
djvused ファイルの文字列は C 言語の文字列に似ています。文字列はダブルクォーテーション
で囲まれた文字です。バックスラッシュ(「\\」)で始まる文字シーケンスには
特別な意味があります。
1 から 3 桁の数字の前のバックスラッシュは、バイト値の 10 進数表現です。
.BR a "、" b "、" t "、" n "、" v "、" f "、" r
に続くバックスラッシュはそれぞれ文字コード 8 から 13 を示しています。その他の文字
の前のバックスラッシュはそれぞれの文字を示します。特に、ダブルクォーテーションの
前のバックスラッシュはダブルクォーテーションを示し、文字列の終了位置を示すものでは
ありません。
.IP リスト:
リストはブランクと括弧で囲まれた一続きの式です。全てのタイプの式をリストに含めることが可能で、
サブリストを含めることもできます。

.SS テキストの書式
テキストの書式は基本的にはテキストの各構造化コンポーネント
を表すリストです。構造化コンポーネントは以下の形式です:
.IP "" 3
.BI "(" "type" " " "xmin" " " "xmax" " " "ymin" " " "ymax" " ... )"
.PP

シンボル
.I type
は、
.BR page "、" column "、" region "、" para "、" line "、" word "、" char
(優先度順)のうちのどれか一つでなくてはなりません。
整数
.IR xmin "、" xmax "、" ymin "、" ymax
は四角形の座標を示し、ページ中の構造化コンポーネントの位置を表します。
座標の単位はピクセルで、起点はページの左下隅です。リスト中の他の式は、いずれも
この構造化コンポーネントに関連付けられたエンコード済みのテキストを表す一つの
文字列か、より順位の低いタイプの構造化コンポーネントです。
.PP
各ページのテキストは単にタイプ
.BR page
の一つの構造化要素で表します。
様々な構造化情報のレベルが使用可能です。たとえば、ページレベルのコンポーネントは
ページレベルの文字列を定義するだけかもしれないし、行のリストかもしれないし、
あるいは文字レベルまでの完全なヒエラルキーを提供するかもしれません。

.SS アノテーションの書式
アノテーションは一連のアノテーション式で表します。以下のアノテーション式が
有効です:
.TP
.BI "(background " color ")"
DjVu 画像の周りの部分の色を指定します。色は X11 の 16 進数表記
.BR #RRGGBB
で指定します。
たとえば、
.B #000000
は黒、
.B #FFFFFF
は白。
.TP
.BI "(zoom " zoomvalue ")"
画像の最初の拡大率を指定します。
引数
.I zoomvalue
は
.BR stretch "、" one2one "、" width "、" page
のいずれかか、文字
.B d
に続けて 1 から 999 間での拡大率を示す数字
(.BR d300 "とか" d150
など)
を指定します。
.TP
.BI "(mode " modevalue ")"
画像の初期表示モードを指定します。
引数
.I modevalue
は
.BR color "、" bw "、" fore "、" black
のうちどれか一つを指定します。
.TP
.BI "(align " horzalign " " vertalign ")"
ビューア上での画像のアラインメントを指定します。
デフォルトでは画像はセンターに表示されます。
引数
.I horzalign
は
.BR left "、" center "、" right
のうちのどれか一つです。
引数
.I vertalign
は
.BR top "、" center "、" bottom
のうちどれか一つです。
.TP
.BI "(maparea " url " " comment " " area " ...)"
指定したリンク先へのハイパーリンクを定義します。
.RS
.PP
引数
.I url
は以下のいずれかの形式を指定します:
.IP "" 3
.I href
.br
.BI "(url " href " " target ")" 
.br
.PP
.I href
は
リンク先を示す文字列で、
.I target 
は
.SM HTML
のアンカータグ
.SM <A>
に定義されているハイパーリンクのターゲットフレームを示します。
リンク先文字列
.I href
は任意の
.SM URL
または、シャープ記号「#」に続けてコンポーネントファイルの識別子、
またはページ番号を指定することが出来ます。ページ番号には
ページを置き換えるためのオプション記号をつけることが出来ます。
たとえば、
.B """#-1""" 
や
.B """#+1"""
は前のページまたは次のページを表します。

引数
.I comment
はユーザがビューアのハイパーリンク上をマウスで動かした
ときに表示される文字列です。

引数
.I area
はハイパーリンクの形や場所を定義します。
以下の形式が使用出来ます:
.IP "" 3
.BI "(rect " xmin " " ymin " " width " " height ")"
.br
.BI "(oval " xmin " " ymin " " width " " height ")"
.br
.BI "(polygon " x0 " " y0 " " x1 " " y1 " ... )"
.PP
全てのパラメータは座標を示す数字です。
座標はピクセルで指定し、起点はページの左下隅です。

.B maparea
リストのその他の式はハイパーリンクに関連付けられた
視覚効果を表します。オプションの最初の部分は
ハイパーリンクエリアの境界線のタイプを定義します:
.IP "" 3
.BI "(xor)"
.br
.BI "(border " color ")"
.br
.BI "(shadow_in [" thickness "])"
.br
.BI "(shadow_out [" thickness "])"
.br
.BI "(shadow_ein [" thickness "])"
.br
.BI "(shadow_eout [" thickness "])"
.PP
パラメータ
.I color
は上述のような
.B #RRGGBB
形式の書式を使用し、
パラメータ
.I thickness
には 1 から 32 の整数を指定します。
最後の 4 つの境界線モードは四角形のハイパーリンクでのみ使用できます。
ユーザがハイパーリンクの上をマウスで動かすと境界線が表示されます。
以下のオプションを指定すると境界線は常に可視になります:
.IP "" 3
.B (border-avis)
.PP
最後に、以下のオプションを四角形のエリアに使用出来ます。
指定した色で領域全体をハイライトさせます。
.IP "" 3
.BI "(hilite " color ")"
.PP
これは画像中の特定の箇所を強調表示するために空の
.SM URL 
とともに使うことがあります。
.RE
.TP
.BI "(metadata ... (" key " " value ") ... )"
メタデータエントリを定義します。
シンボル
.I key
はメタデータエントリの性質を示し、エントリはこのシンボルで識別されます。
典型的なキーには
.BR year "、" booktitle "、" editor "、" author
などがあります。
BibTeX 書誌システムと同じキー名を使用することが提案されています。
文字列
.I value
は対応するキーに関連付けられた値を示します。

.SH 制限
このバージョンの
.B djvused
は一つまたは全てのコンポーネントファイルの選択のみを
サポートしています。ページ一部を選択する方法は
ありません。

.SH クレジット
このプログラムは by L\('eon Bottou <leonb@users.sourceforge.net>
が開発し、
Yann Le Cun <profshadoko@users.sourceforge.net>
Florin Nicsa
Bill Riemers <docbill@sourceforge.net>
その他の方々により改良されました。
この man page は Nobchika Morimoto <morimoto@lizardtech.com>
が翻訳しました。

.SH 参照
.BR djvu (1)、
.BR djvutxt (1)、
.BR djvmcvt (1)、
.BR djvudump (1)、
.BR bzz (1)