.\" -*- coding: euc-jp -*-
.\" Copyright (c) 2001-2003 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\" Copyright (c) 2001 AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVUDUMP 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.de SS
.SH \\0\\0\\0\\$*
..
.SH 名前
djvudump \- DjVu ファイルの内部構造を表示します。

.SH 書式
.BI "djvudump " "djvufiles" "..."

.SH 説明
プログラム
.B djvudump
は DjVu ファイルのチャンク構造の説明をインデントつきで出力します。
各行の説明はチャンク ID とそれに続くチャンクサイズを含みます。各行は IFF ファイルの
ヒエラルキー構造を示すためにインデントされています。バンドルド形式の
マルチページ DjVu 文書の場合、ページの識別子は大括弧の中に出力されます。
.B djvudump
がチャンク名を認識してチャンクデータの処理方法が分かる場合、チャンクの追加情報が
提供されます。

.SH 注意
このプログラムは、実際 Electronic Arts IFF 85 に準拠したあらゆるファイルを
解析することが出来ます。これには様々な画像ファイルやサウンドファイルが含まれます。

.SH クレジット
このプログラムは L\('eon Bottou <leonb@users.sourceforge.net>
が開発し、
Andrei Erofeev <andrew_erofeev@yahoo.com> および
Bill Riemers <docbill@sourceforge.net>
その他の方々により改良されました。
この man page は Nobchika Morimoto <morimoto@lizardtech.com>
が翻訳しました。

.SH 参照
.BR djvu (1)

