.\" -*- coding: euc-jp -*-
.\" Copyright (c) 2003 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\" Copyright (c) 2001 AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVUPS 1 "01/18/2003" "DjVuLibre-3.5" "DjVuLibre-3.5"
.SH 名前
djvups \- DjVu 文書を PostScript へ変換します。

.SH 書式
.BI "djvups  [" "options" "] [" "djvufile" "]"

.SH 説明
このプログラムは DjVu ファイル
.IR djvufile
をデコードして、標準出力に PostScript ファイルを
作成します。PostScript プリンタには様々な機能があります。
良い結果を得るために
.B -level
および
.B -gray
を試して下さい。

.SH オプション
.TP
.BI -page= pagespec
変換する文書のページを指定します。
ページ設定
.I pagespec
はカンマで区切られた複数のページ範囲を指定します。
一つのページ範囲はページ番号、ダッシュで区切られた二つの
ページ番号です。
たとえば
.BR 1-10
は 1 から 10 ページを印刷します。
.BR 1,3,9999-4
は、1 ページと 3 ページ、および全てのページを逆順に
4 ページまで印刷します。
.TP
.BI -format=ps
PostScript ファイルを生成します。これはデフォルトです。
.TP
.BI -format=eps
EPS ファイルを生成します。EPS (Encapsulated PostScript) ファイル
は画像を別の文書へ埋め込むのに適しています。
EPS ファイルには一つのページしか含めることが出来ません。
このオプションを設定すると、
.BR -copies、
.BR -orientation、
.BR -zoom、
.BR -cropmarks、
.BR -booklet
をオーバーライドします。
.TP
.BI -copies= n
印刷部数を指定します。
.TP
.BI -orientation= orient
ページの向きを
.BR auto、
.BR portrait、
.B landscape
で指定します。
.TP
.BI -mode= modespec
ページのデコード方法を指定します。
Specify how pages should be decoded.
デフォルトモードの
.BR color
は DjVu 文書の全てのレイヤを描画します。
.BR black
モードは前景レイヤのマスクのみを描画します。DjVuPhoto 画像は前景レイヤの
マスクがないのでこのモードはでは動作しません。
.BR foreground
および
.BR background
モードは DjVuDocument 画像の前景レイヤまたは背景レイヤのみを描画します。
.TP
.BI -zoom= zoomspec
拡大率
.IR zoomspec
を指定します。
デフォルトは
.BR auto
で、画像をページに合わせてスケーリングします。
引数
.I zoomspec
はオリジナル文書のサイズに対して拡大率を
パーセンテージで
.BR 25
から
.BR 2400
の範囲で指定することも可能です。
.TP
.BI -frame= yesno
.BR yes
を指定すると文書のページの境界を示す細いグレーの境界線を
出力します。
デフォルトは
.BR no
です。
.TP
.BI -cropmarks= yesno
.BR yes
を指定するとページの切り取り線を出力します。
デフォルトは
.BR no
です。
.TP
.BI -level= languagelevel
PostScript の言語レベルを指定します。
Select the language level of the generated PostScript.
有効な
.IR languagelevel
の値は
.BR 1、
.BR 2、
.BR 3
です。
レベル
.B 3
は最もコンパクトで高速な PostScrit ファイルを生成します。
しかし、これらのファイルを印刷するには最新のプリンタが必要です。
レベル
.B 2
がデフォルト値です。
生成された PostScript ファイルの多くは小さく、旧式の
PostScript プリンタでなければ動作します。
レベル
.B 1
は上記のどれもうまくいかない場合のオプションです。
.TP
.BI -color= yesno
デフォルト値の
.BR yes
はカラーの PostScript ファイルを生成します。
.BR no
を指定するとグレイスケールに変換します。
生成された PostScript ファイルは小さく、
少し扱いやすくなります。
.TP
.BI -gray
このオプションは
.BR -color=no
と同じで、便宜的に用意されています。
.TP
.BI -colormatch= yesno
デフォルト値
.BR yes
では
.SM sRGB
に対応したデバイスに依存しない色で PostScript ファイル
を生成します。
最新のプリンタでは出来るだけオリジナルに近づけようとします。
.B no
を指定するとデバイス依存のカラーで PostScript ファイルを生成します。
旧式のプリンタでは便利です。
その場合は、
.BR -gamma
を指定してカラー補正します。
.TP
.BI -gamma= gammaspec
デバイス依存の PostScript カラーでガンマ補正値を指定します。
引数
.I gammaspec
は
.B 0.3
から
.BR 5.0
の範囲である必要があります。
ガンマ補正は通常 CRT にのみ適しています。
プリンタの中にはデバイス依存の RGB カラーを CRT のカラー情報に
エミュレートするものがあります。
.TP
.BI -booklet= opt
冊子印刷モードをオンにします。
冊子モードは用紙を折り曲げて冊子を作成するのに
最適なように二つのページを両面に印刷します。
オプション
.I opt
に
.B no
を指定すると冊子モードを無効にし、
.B yes
では
見開き冊子モード、
.B recto
で右ページ片面モード、
.B verso
で左ページ片面モードをそれぞれ有効にします。
.TP
.BI -bookletmax= max
冊子ごとの最大ページ数を指定します。
一回の印刷で複数の冊子を作成することが出来ます。
引数
.I max
は 4 の倍数で切り上げられます。
.B 0
を指定すると最大値が設定されず、全てが一つの冊子に
まとめられます。これはデフォルトです。
.TP
.BI -bookletalign= align
各用紙の左ページに適用されるプラスまたは
マイナスのオフセット値を指定します。
引数
.I align
はポイントで指定します(1 ポイントは 1/72 インチ、0.352 ミリ)。
ある種のプリンタでは左右のページを正しく整列させることが出来ます。
デフォルト値は
.BR 0
です。
.TP
.BI -bookletfold= base[+incr]
1 枚の用紙中の両方のページのマージンを指定します。
元になる値
.I base
はポイントで表します (1 ポイントは 1/72 インチ、0.352 ミリ)。
このマージンは用紙が外側になるにつれて
.I incr
ミリポイントで指定した値ずつ増えていきます。
デフォルト値は
.BR 18+200
です。

.SH クレジット
このプログラムは L\('eon Bottou <leonb@users.sourceforge.net>、
Andrei Erofeev <andrew_erofeev@yahoo.com>、
および
Florin Nicsa
が開発しました。
この man page は Nobchika Morimoto <morimoto@lizardtech.com>
が翻訳しました。

.SH 参照
.BR djvu (1)、
.BR ddjvu (1)、
.BR djview (1)
