.\" -*- coding: euc-jp -*-
.\" Copyright (c) 2001-2003 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\" Copyright (c) 2001 AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVUMAKE 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.de SS
.SH \\0\\0\\0\\$*
..
.SH 名前
djvumake \- DjVu 画像ファイルを結合します。

.SH 書式
.BI "djvumake " "djvufile" " [" "chkid" "=" "argument" "]..." 

.SH 説明
プログラム
.B djvumake
は
シングルページの DjVu ファイル
.I djvufile
を結合して、指定された引数に従ってコピーしたりチャンクを新たに作成したりします。
サポートされる引数は以下のとおり:
.TP
.BI INFO= w , h , dpi
情報チャンクを作成します。引数
.IR w "、" h "、" dpi
は、幅、高さ解像度を示します。全ての引数は省略することが出来ます。
デフォルトの解像度は 300 DPI です。デフォルトの幅と高さは、コマンドライン
オプションの最初のマスクチャンクから取得されます。
.TP
.BI Sjbz= jb2file
.SM JB2
前景マスクチャンクを作成します。ファイル
.I jb2file
は生の JB2 データ、またはプログラム
.BR cjb2
で作成した JB2 データを含む DjVu ファイルを指定することが出来ます。
.TP
.BI Smmr= mmrfile
.SM MMR/G4
前景マスクチャンクを作成します。ファイル
.I mmrfile
は生の MMR データ、または MMR データを含む
DjVu ファイルを指定することが出来ます。
.TP
.BI BG44= iw44file "[:" n "]"
一つまたは複数の
.SM IW44
背景チャンクを作成します。ファイル
.I iw44file
は
.SM IW44 
データを含んでいる必要があります。
このようなファイルは背景画像をプログラム
.B c44
で圧縮して、プログラム
.BR djvuextract
で生の
.SM IW44
データを取り出すことで得られます。
オプション引数
.I n
は IW44 ファイルからコピーするチャンクの数を示します。
チャンク数を省略すると全ての使用可能なチャンクをコピーします。
.TP
.BI BGjp= jpegfile
.SM JPEG
エンコードの背景チャンクを作成します。
ファイル
.I jpegfile
は
.SM JPEG
エンコードのデータである必要があります。
.TP
.BI BG2k= jpegfile
.SM JPEG-2000
の背景チャンクを作成します。
ファイル
.I jpegfile
は
.SM JPEG-2000
エンコードのデータである必要があります。
現バージョンの DjVu デコーダは JPEG-2000 データを含むファイルの描画には対応しておりません。
.TP
.BI FGbz= bzzfile
各
.SM JB2
エンコードのチャンクに一つの色を持つ前景カラーチャンクを作成します。
ファイル
.I bzzfile
は
.BR djvuextract
コマンドを使用して既存の DjVu ファイルからチャンクデータを取り出し
作成するのが最善の方法です。
.TP
.BI FG44= iw44file
.SM IW44
前景カラーチャンクを作成します。
ファイル
.I iw44file
は
.SM IW44
データである必要があります。
このようなファイルは背景画像をコマンド
.B c44
で圧縮して、プログラム
.BR djvuextract
で生の
.SM IW44 
データを取り出すことで得られます。
最初のチャンクのみがコピーされます。
.TP
.BI FGjp= jpegfile
.SM JPEG
の前景カラーチャンクを作成します。
.TP
.BI FG2k= jpegfile
.SM JPEG-2000
の前景カラーチャンクを作成します。
現バージョンの DjVu デコーダは JPEG-2000 データを含むファイルの描画には対応しておりません。
.TP
.BI INCL= fileid
.IR fileid
に指定された名前のコンポーネントファイルをさす DjVu3 形式のインクルードチャンク
を作成します。
出力されるファイルは
.BR djvm
コマンドを使用してマルチページ文書化する必要があります。
.TP 
.BI PPM= ppmfile
.SM PPM
ファイル
.IR ppmfile
をマスキングおよびサブサンプルして
.SM IW44
背景チャンク、および
.SM IW44 
前景カラーチャンクを作成します。

たとえば、
.SM PPM
形式の画像
.B myimage.ppm
と、全く同じサイズで、黒ピクセルが前景に属するものとそうでないものを
示している
.SM PBM
白黒画像
.B mymask.pbm
があるとします。この場合以下の二つのコマンドを使用して DjVuDocument を
作成することが出来ます:
.IP "" 3
.B cjb2 mymask.pbm mymask.djvu
.br
.B djvumake my.djvu Sjbz=mymask.djvu PPM=myimage.ppm
.br
.br
.PP
正規の DjVu ファイルの構成については DjVu の仕様
(
.B http://www.djvuzone.org/djvu/djvu/djvuspec/
)をご覧ください。

.SH クレジット
このプログラムは L\('eon Bottou <leonb@users.sourceforge.net>
が開発し、
Andrei Erofeev <andrew_erofeev@yahoo.com> および
Bill Riemers <docbill@sourceforge.net>
その他の方々により改良されました。
この man page は Nobchika Morimoto <morimoto@lizardtech.com>
が翻訳しました。

.SH 参照
.BR djvu (1)、
.BR djvuextract (1)、
.BR cjb2 (1)、
.BR c44 (1)
